import type { Unit } from '../../types/content'
import { au, img } from '../helpers'

export const unit05: Unit = {
  id: 'unit-5',
  number: 5,
  title: 'news',
  phrase: 'talk about the news, plan a campaign and make predictions',
  overviewPage: 55,
  pages: [55, 66],
  intro:
    'In this unit you read and listen to news stories, talk about fake news, plan a campaign, give and respond to personal news, and plan a news app for the future.',
  objectives: [
    '5A – read an article about fake news; talk about a news story',
    '5B – understand a podcast about young people in the news; plan a campaign',
    '5C – give and respond to personal news',
    '5D – understand people talking about the news; plan a news app',
  ],
  video: [
    {
      title: 'BBC Vlogs: How do you get your news?',
      file: 'SO3 B1 U5 BBC Vlogs.mp4',
      page: 55,
    },
    {
      title: 'BBC Street Interviews: The future of news',
      file: 'SO3 B1 U5 BBC StreetInt.mp4',
      page: 64,
    },
  ],
  lessons: [
    {
      id: '5a',
      code: '5A',
      title: 'Fake news',
      pages: [56, 58],
      labels: {
        grammar: 'relative clauses',
        vocabulary: 'news and social media',
        pronunciation: 'wh-',
      },
      objectives: ['read an article about fake news', 'use relative clauses', 'talk about a news story'],
      blocks: [
        {
          type: 'text',
          title: 'The news that travels fast',
          titleAr: 'الأخبار التي تنتشر بسرعة',
          paragraphs: [
            'Christopher Blair, who lives on the U.S. East Coast, is one of the world\u2019s most creative news writers. He isn\u2019t a journalist who writes articles for a newspaper. He writes news stories which are not true. He invents them and publishes them online.',
            'He writes about anything: politics, a famous athlete or someone who has been in the news recently. First, he writes a headline which will get attention. Then, he adds a few details and before long, he has written a blog post, which is about 200 words long. Sometimes he gets thousands of views in just minutes.',
            'Maarten Schenk, who lives in a small town near Brussels, Belgium, works from home. He sits at his desk in front of three computer screens. One day he notices a lot of activity: the USA is waking up, and there\u2019s a news story which is being shared by lots of people on Facebook. Schenk is a man who likes to find out the truth. He does some fact-checking and starts to type. His job is to tell the world that what he\u2019s seeing online is completely invented. It\u2019s fake news.',
          ],
        },
        {
          type: 'vocab',
          title: 'news and social media',
          titleAr: 'الأخبار ووسائل التواصل الاجتماعي',
          items: [
            { word: 'publish', meaning: 'make a story available for other people to read, in print or online', meaningAr: 'ينشر' },
            { word: 'journalist', meaning: 'someone who writes about the news for a newspaper, radio, TV, etc.', meaningAr: 'صحفي' },
            { word: 'find out', meaning: 'to discover information', meaningAr: 'يكتشف / يعرف معلومة' },
            { word: 'post', meaning: 'upload a story on the internet', meaningAr: 'ينشر على الإنترنت' },
            { word: 'headline', meaning: 'the title of a story in the news, usually printed in large letters', meaningAr: 'العنوان الرئيسي (المانشيت)' },
            { word: 'fake news', meaning: 'news that is invented and not true', meaningAr: 'الأخبار المزيفة' },
            { word: 'the facts', meaning: 'the main information in the news story', meaningAr: 'الحقائق' },
            { word: 'blog post', meaning: 'an article on someone\u2019s personal webpage', meaningAr: 'تدوينة / مقال في مدونة' },
            { word: 'go viral', meaning: 'spread very quickly across the internet', meaningAr: 'ينتشر بسرعة على الإنترنت' },
            { word: 'spot', meaning: 'see or notice', meaningAr: 'يلاحظ / يرى', example: 'I think it\u2019s pretty easy to spot this kind of story.', exampleAr: 'أعتقد أنه من السهل جداً ملاحظة هذا النوع من الأخبار.' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u5-5a-vocab',
            title: '5A Vocabulary',
            kind: 'fill-blank',
            instructions: 'Complete the sentences with the correct form of a word from Lesson 5A.',
            instructionsAr: 'أكمل الجمل بالصيغة الصحيحة لكلمة من الدرس 5A.',
            page: 57,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'I sometimes',
                answer: 'post',
                after: 'my own ideas online on social media.',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'When I look at newspapers I never read a full article - I only read the',
                answer: 'headlines',
                after: '.',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: 'I think it\u2019s difficult to',
                answer: 'spot',
                after: 'if a story is fake news.',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'I think it\u2019s important for',
                answer: 'journalists',
                after: 'who write for newspapers to check the facts.',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: 'I try to write a',
                answer: 'blog post',
                after: 'twice a week, sharing my thoughts and feelings.',
              },
            ],
          },
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u5-5a-tf',
            title: 'The article: True or False?',
            kind: 'true-false',
            instructions: 'Read the article again. Are the statements True (T) or False (F)?',
            instructionsAr: 'اقرأ المقال مرة أخرى. هل العبارات صحيحة (T) أم خاطئة (F)؟',
            page: 56,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'true-false',
                statement: 'Christopher Blair works for a traditional newspaper.',
                correct: false,
              },
              {
                id: 'q2',
                kind: 'true-false',
                statement: 'Blair always writes news stories about similar topics.',
                correct: false,
              },
              {
                id: 'q3',
                kind: 'true-false',
                statement: 'Maarten Schenk needs to work quickly to discover the real facts about a story.',
                correct: true,
              },
              {
                id: 'q4',
                kind: 'true-false',
                statement: 'Schenk is often unable to stop a fake news story from spreading.',
                correct: true,
              },
              {
                id: 'q5',
                kind: 'true-false',
                statement: 'Christopher Blair and Maarten Schenk are working against one another.',
                correct: false,
              },
              {
                id: 'q6',
                kind: 'true-false',
                statement: 'People who write fake news are not motivated by money.',
                correct: false,
              },
              {
                id: 'q7',
                kind: 'true-false',
                statement: 'Fact checkers are used by social media companies to reduce the amount of fake news.',
                correct: true,
              },
            ],
          },
        },
        {
          type: 'grammar',
          title: 'relative clauses',
          titleAr: 'جمل الوصل (الموصولة)',
          explanation:
            'Relative clauses give extra information about a person, thing, place or time. They start with a relative pronoun: who (people), which (things), where (places), when (times) and whose (possession).',
          explanationAr:
            'تعطي جمل الوصل معلومات إضافية عن شخص أو شيء أو مكان أو وقت. تبدأ بضمير موصول: who (للأشخاص) و which (للأشياء) و where (للأماكن) و when (للأوقات) و whose (للملكية).',
          rule: 'who = people, which = things, where = places, when = times, whose = possession. That can replace who or which in defining relative clauses.',
          ruleAr: 'who = الأشخاص، which = الأشياء، where = الأماكن، when = الأوقات، whose = الملكية. يمكن أن تحل that محل who أو which في جمل الوصل المحددة.',
          table: {
            headers: ['Relative pronoun', 'Use', 'Example'],
            rows: [
              { values: ['who', 'people', 'Christopher Blair is a journalist who writes fake news.'] },
              { values: ['which', 'things', 'He writes news stories which are completely fake.'] },
              { values: ['where', 'places', 'This is the room where Maarten Schenk works.'] },
              { values: ['when', 'times', 'He makes a note of the time when a story is first shared on social media.'] },
              { values: ['whose', 'possession', 'This is the politician whose story went viral.'] },
            ],
          },
          examples: [
            "Books about the history of flight often say it was the Wright brothers.",
            'The whale, which was picked up by the powerful winds of Hurricane Delta, was 15 m long.',
            'The boys, who were aged eight, ten and twelve, let the spider bite them.',
          ],
          bankPage: 120,
          videos: [
            { id: 'W-uPiTB877c', title: 'Complex Sentences in English Writing - Learn How to Make Complex Sentences' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u5-5a-relatives',
            title: 'Relative clauses',
            kind: 'fill-blank',
            instructions: 'Complete the sentences with who, which, when, where or whose.',
            instructionsAr: 'أكمل الجمل بـ who أو which أو when أو where أو whose.',
            page: 58,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'Christopher Blair is a journalist',
                answer: 'who',
                after: 'writes fake news.',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'He writes news stories',
                answer: 'which',
                after: 'are completely fake.',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: 'This is the room',
                answer: 'where',
                after: 'Maarten Schenk works.',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'He makes a note of the time',
                answer: 'when',
                after: 'a story is first shared on social media.',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: 'This is the politician',
                answer: 'whose',
                after: 'story went viral.',
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Pronunciation: wh-',
          titleAr: 'النطق: wh-',
          tracks: au(['5.01', '5.02'], 58),
        },
        {
          type: 'text',
          title: 'Three news stories to retell',
          titleAr: 'ثلاث أخبار لإعادة سردها',
          paragraphs: [
            'Reading 1: "WHALE LANDS IN FARMER\u2019S FIELD" - A 30,000 kg whale landed in a farmer\u2019s field in Arkadelphia, 482 km off the coast of Louisiana. The whale, which was picked up by the powerful winds of Hurricane Delta, was 15 m long.',
            'Reading 2: "SPIDERBITE!" - Three brothers from La Paz, Bolivia, were taken to hospital after being bitten by a black widow spider. The boys, who were aged eight, ten and twelve, let the spider bite them because they wanted to develop superpowers.',
            'Reading 3: "YOUR PIZZA DELIVERY!" - A man who lives in Belgium keeps receiving pizzas which he never orders. For nearly ten years, deliveries of pizzas and other fast food arrive at his house, but he never orders them.',
          ],
        },
        {
          type: 'pages',
          images: [img(70, 'Lesson 5A, page 56'), img(71, 'Lesson 5A, page 57'), img(72, 'Lesson 5A, page 58')],
        },
      ],
    },
    {
      id: '5b',
      code: '5B',
      title: 'Newsmakers',
      pages: [59, 61],
      labels: {
        grammar: 'reported speech',
        vocabulary: 'social issues; the environment',
        pronunciation: 'silent letters',
      },
      objectives: ['understand a podcast about young people in the news', 'use reported speech', 'plan a campaign and write an online comment'],
      blocks: [
        {
          type: 'text',
          title: 'In the news',
          titleAr: 'في الأخبار',
          paragraphs: [
            'High levels of pollution found in cities: scientists report that there is increasing pollution in many cities around the world. It is thought that the increasing number of cars in cities is to blame.',
            'Schoolchildren remove waste from a beach to protect the environment: over a hundred children spent the day collecting plastic, tin cans and paper cups from a beach in Cornwall, UK.',
            'Teenagers collect coins for charity: Magda Kowalski, 14, and Jan Bartosz, 15, of Katowice raised over 2,500 for two charities, Children in Need and Food for the Poor.',
            'Campaign against killing of elephants: yesterday thousands of people walked through the streets of Nairobi, Kenya, calling for new laws to protect elephants.',
            'Activists start a campaign to recycle old car parts: a small town in New Zealand is taking old cars and using their parts to create works of art.',
            'Local company donates $10,000 to charity: a fishing company has given $10,000 to a group that works to save whales.',
          ],
        },
        {
          type: 'vocab',
          title: 'social issues; the environment',
          titleAr: 'قضايا اجتماعية؛ البيئة',
          items: [
            { word: 'pollution', meaning: 'the amount of dirt or unwanted objects in the environment', meaningAr: 'التلوّث' },
            { word: 'level', meaning: 'the amount or number of something', meaningAr: 'المستوى / المقدار', example: 'Levels of pollution means the amount of dirt or unwanted objects in the environment.', exampleAr: 'مستويات التلوّث تعني مقدار الأوساخ أو المواد غير المرغوبة في البيئة.' },
            { word: 'recycle', meaning: 'use things again instead of throwing them away', meaningAr: 'يعيد التدوير' },
            { word: 'waste', meaning: 'unwanted things, e.g. plastic and old objects', meaningAr: 'النفايات / المخلفات' },
            { word: 'campaign', meaning: 'a programme of planned actions to achieve something', meaningAr: 'حملة' },
            { word: 'activists', meaning: 'people who take action to create change', meaningAr: 'ناشطون' },
            { word: 'collect', meaning: 'gather things together', meaningAr: 'يجمع' },
            { word: 'charity', meaning: 'an organisation that helps people in need', meaningAr: 'جمعية خيرية' },
            { word: 'donate', meaning: 'give money or things to help people', meaningAr: 'يتبرّع' },
            { word: 'environment', meaning: 'the natural world around us', meaningAr: 'البيئة' },
          ],
          source: 'See also Vocabulary Bank, page 141 (the environment)',
        },
        {
          type: 'audio',
          title: 'Pronunciation: silent letters',
          titleAr: 'النطق: الحروف الصامتة',
          tracks: au(['5.03'], 59),
        },
        {
          type: 'text',
          title: 'Podcast: Young people in the news',
          titleAr: 'بودكاست: الشباب في الأخبار',
          paragraphs: [
            'Yash Gupta: as a high school student he collected glasses and started a charity to donate them to students who couldn\u2019t afford them. His charity has helped thousands of people.',
            'Melati and Isabel Wijsen: they started a campaign against plastic bags in Bali when they were teenagers. Because of their campaign, in 2019 Bali banned single-use plastic bags.',
            'Kelvin Doe: he started working with technology when he was thirteen. He builds his inventions from materials he finds - old wires, batteries and objects that other people throw away.',
          ],
        },
        {
          type: 'audio',
          title: 'Podcast: listen and answer',
          titleAr: 'بودكاست: استمع وأجب',
          tracks: au(['5.04'], 60),
        },
        {
          type: 'grammar',
          title: 'reported speech',
          titleAr: 'الكلام المنقول',
          explanation:
            'When we report what someone said, we usually move the tense back one step (backshift) and change pronouns and other words.',
          explanationAr:
            'عندما ننقل ما قاله شخص ما، نُرجّع الزمن خطوة إلى الوراء ونغيّر الضمائر والكلمات الأخرى.',
          rule: "present → past: 'He is a genius' → his friends said that he was a genius. present perfect → past perfect: 'It has changed my life' → it had changed his life. will → would: 'Bali will ban single-use plastic bags' → the governor said that Bali would ban single-use plastic bags.",
          ruleAr: 'المضارع → الماضي: "He is a genius" → قال أصدقاؤه إنه كان عبقرياً. المضارع التام → الماضي التام: "It has changed my life" → غيّر حياته. will → would: "Bali will ban single-use plastic bags" → قال الحاكم إن بالي ستحظر الأكياس البلاستيكية ذات الاستعمال الواحد.',
          table: {
            headers: ['Direct speech', 'Reported speech'],
            rows: [
              { values: ['"He is a genius."', 'His friends said that he was a genius.'] },
              { values: ["\u201cIt has changed my life.\u201d", "One child in Mexico told us that it had changed his life."] },
              { values: ["\u201cBali will ban single-use plastic bags.\u201d", "The governor said that Bali would ban single-use plastic bags."] },
            ],
          },
          examples: [
            'His friends said that he was a genius.',
            'One child in Mexico told us that it had changed his life.',
            'The governor said that Bali would ban single-use plastic bags.',
          ],
          bankPage: 121,
          videos: [
            { id: 'W-uPiTB877c', title: 'Complex Sentences in English Writing - Learn How to Make Complex Sentences' },
            { id: 'hk4MjcRdTgc', title: 'English Verb Tenses Guide - Learn About Simple, Perfect, and Continuous Tenses' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u5-5b-reported',
            title: 'Reported speech',
            kind: 'fill-blank',
            instructions: 'Read the direct speech, then complete the reported speech.',
            instructionsAr: 'اقرأ الكلام المباشر، ثم أكمل الكلام المنقول.',
            page: 66,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: "\u201cI never buy newspapers\u201d\nJack said",
                answer: 'that he never bought newspapers',
                after: '.',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: "\u201cI watched a really interesting programme about fake news.\u201d\nJade told me that she",
                answer: 'had watched',
                after: 'a really interesting programme about fake news.',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: "\u201cWe aren't going to buy a new car\u201d\nMy parents said",
                answer: 'that they were not going to buy',
                after: 'a new car.',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: "\u201cI'll help with the party\u201d\nMy sister told me that she",
                answer: 'would help with',
                accept: ["'d help with"],
                after: 'the party.',
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'Writing: an online comment',
          titleAr: 'الكتابة: تعليق على الإنترنت',
          paragraphs: [
            'A local newspaper reports a problem: Bawlyn Beach has become polluted. In July and August there are a lot of parties, and there aren\u2019t enough rubbish bins on the beach. People leave a lot of plastic, cans and other rubbish.',
            'A reader (Nellie Abberly, Vice Principal) responds with solutions: organise groups of young people to do clean-up projects; ask the local government for more rubbish bins; start a recycling project, for example collecting plastic from the beach.',
            'Phrases that introduce a problem: The issue is that\u2026 Unfortunately,\u2026 This issue is becoming more serious every year. Phrases that introduce a solution: One idea is to\u2026 Another suggestion is to\u2026 It would also be good to\u2026',
          ],
        },
        {
          type: 'pages',
          images: [img(73, 'Lesson 5B, page 59'), img(74, 'Lesson 5B, page 60'), img(75, 'Lesson 5B, page 61')],
        },
      ],
    },
    {
      id: '5c',
      code: '5C',
      title: 'Good news',
      pages: [62, 63],
      labels: {
        grammar: 'How to\u2026 give and respond to personal news',
        vocabulary: 'events and occasions',
        pronunciation: 'intonation to exaggerate feelings',
      },
      objectives: ['give and respond to personal news', 'talk about events and occasions'],
      blocks: [
        {
          type: 'vocab',
          title: 'events and occasions',
          titleAr: 'الأحداث والمناسبات',
          items: [
            { word: 'pass your exams/driving test', meaning: 'succeed in a test', meaningAr: 'ينجح في الامتحانات/اختبار القيادة', example: 'I passed my driving test.', exampleAr: 'نجحت في اختبار القيادة.' },
            { word: 'fail your exams/driving test', meaning: 'not succeed in a test', meaningAr: 'يرسب في الامتحانات/اختبار القيادة', example: 'I failed my accountancy exams for the third time.', exampleAr: 'رسبت في امتحانات المحاسبة للمرة الثالثة.' },
            { word: 'have a baby', meaning: 'give birth to a child', meaningAr: 'يُرزق بمولود', example: 'Lolita was born on Saturday.', exampleAr: 'وُلدت لوليتا يوم السبت.' },
            { word: 'lose your job', meaning: 'be sacked', meaningAr: 'يفقد وظيفته', example: 'I\u2019m now worried I might lose my job.', exampleAr: 'أنا الآن قلق من أنني قد أفقد وظيفتي.' },
            { word: 'get promoted / a new job', meaning: 'get a higher position or a new job', meaningAr: 'يُرقّى / يحصل على وظيفة جديدة', example: 'I got promoted, so I\u2019m now earning more money.', exampleAr: 'لقد ترقّيت، لذا أكسب الآن مالاً أكثر.' },
            { word: 'have an argument', meaning: 'disagree angrily', meaningAr: 'يتشاجر / يجادل', example: 'I had an argument with a friend.', exampleAr: 'تجادلت مع صديق.' },
            { word: 'win a competition/match', meaning: 'come first in a competition', meaningAr: 'يفوز في مسابقة/مباراة', example: 'I won a competition and got a prize.', exampleAr: 'فزت في مسابقة وحصلت على جائزة.' },
            { word: 'get engaged/married', meaning: 'agree to marry / get married', meaningAr: 'يخطب / يتزوّج', example: 'We\u2019re getting married in the summer.', exampleAr: 'سنتزوّج في الصيف.' },
            { word: 'break your phone/laptop', meaning: 'accidentally damage it', meaningAr: 'يكسر هاتفه/حاسوبه', example: 'I broke my phone.', exampleAr: 'كسرت هاتفي.' },
            { word: 'get 2,000 likes', meaning: 'receive 2,000 likes online', meaningAr: 'يحصل على 2000 إعجاب', example: 'My video got over 2,000 likes!', exampleAr: 'حصل مقطع الفيديو الخاص بي على أكثر من 2000 إعجاب!' },
            { word: 'graduate from university', meaning: 'finish university studies', meaningAr: 'يتخرّج من الجامعة', example: 'I graduated from university last year.', exampleAr: 'تخرّجت من الجامعة العام الماضي.' },
            { word: 'move house', meaning: 'go and live in a new house', meaningAr: 'ينتقل للسكن في منزل جديد', example: 'I\u2019ve just moved into a really nice house.', exampleAr: 'لقد انتقلت للتو إلى منزل جميل جداً.' },
            { word: 'have your birthday', meaning: 'celebrate your birthday', meaningAr: 'يحتفل بعيد ميلاده', example: 'How did you have your last birthday?', exampleAr: 'كيف احتفلت بعيد ميلادك الماضي؟' },
            { word: 'quit your job', meaning: 'leave your job', meaningAr: 'يترك وظيفته', example: 'I\u2019m thinking about quitting my job.', exampleAr: 'أفكر في ترك وظيفتي.' },
            { word: 'celebrate', meaning: 'do something fun for a special occasion', meaningAr: 'يحتفل', example: 'We\u2019re having a party for my 40th.', exampleAr: 'سنقيم حفلة لعيد ميلادي الأربعين.' },
          ],
        },
        {
          type: 'text',
          title: 'Good news and bad news',
          titleAr: 'أخبار جيدة وأخبار سيئة',
          paragraphs: [
            'The best week ever! Elena says: "I can\u2019t believe it. I\u2019ve just moved into a really nice house, and I passed my driving test. Work\u2019s going really well. I got promoted, so I\u2019m now earning more money. My sister has had a baby, so now I\u2019m an aunt. I also posted a video online of me singing with my band and it got over 2,000 likes!"',
            'What about Tomas? "I\u2019m having a terrible week! I failed my accountancy exams for the third time. I\u2019m now worried I might lose my job. I broke my phone. I had an argument with a friend and now he isn\u2019t speaking to me. And I\u2019ve got my driving test tomorrow - I\u2019ll probably fail!"',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u5-5c-news-mcq',
            title: 'How to\u2026 give and respond to personal news',
            kind: 'mcq',
            instructions: 'Choose the correct phrase.',
            instructionsAr: 'اختر العبارة الصحيحة.',
            page: 63,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'Introducing good news:',
                options: [
                  { label: 'I\u2019ve got some good news to tell you.', correct: true },
                  { label: 'Bad news, I\u2019m afraid\u2026', correct: false },
                  { label: 'Unfortunately,\u2026', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'Introducing bad news:',
                options: [
                  { label: 'There\u2019s something I need to tell you.', correct: true },
                  { label: 'I\u2019m really pleased to tell you\u2026', correct: false },
                  { label: 'I\u2019ve got some amazing news!', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'Responding to good news:',
                options: [
                  { label: 'Wow, that\u2019s amazing!', correct: true },
                  { label: 'Oh no! That\u2019s awful.', correct: false },
                  { label: 'I\u2019m really sorry to hear that.', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'Responding to bad news:',
                options: [
                  { label: 'I\u2019m really sorry.', correct: true },
                  { label: 'Congratulations!', correct: false },
                  { label: 'That\u2019s awesome!', correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'A friend tells you they passed their exam. React:',
                options: [
                  { label: 'Well done! I\u2019m so pleased for you.', correct: true },
                  { label: 'What a shame.', correct: false },
                  { label: 'I\u2019m really sorry to hear that.', correct: false },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'A friend tells you she lost her job. React:',
                options: [
                  { label: 'I\u2019m so sorry to hear that.', correct: true },
                  { label: 'That\u2019s fantastic news!', correct: false },
                  { label: 'Congratulations!', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Pronunciation: intonation to exaggerate feelings',
          titleAr: 'النطق: التنغيم للمبالغة في المشاعر',
          tracks: au(['5.05', '5.06', '5.07'], 63),
        },
        {
          type: 'callout',
          title: 'Note',
          titleAr: 'ملاحظة',
          tone: 'tip',
          text: 'When we respond to news, we can exaggerate our feelings by stressing the vowel sounds and making them longer: "Wow, that\u2019s awesome!" The speakers in the audio use intonation to exaggerate their feelings.',
          textAr: 'عندما نرد على الأخبار، يمكننا المبالغة في مشاعرنا بالتشديد على أصوات الحروف وإطالتها: «واو، هذا رائع!» يستخدم المتحدثون في المقطع الصوتي التنغيم للمبالغة في مشاعرهم.',
        },
        {
          type: 'pages',
          images: [img(76, 'Lesson 5C, page 62'), img(77, 'Lesson 5C, page 63')],
        },
      ],
    },
    {
      id: '5d',
      code: '5D',
      title: 'The future of news',
      pages: [64, 65],
      labels: {
        grammar: 'will, might and be going to for predictions',
        skills: 'plan a news app',
      },
      objectives: ['understand people talking about the news', 'use will, might and be going to for predictions', 'plan a news app and write a webpage'],
      blocks: [
        {
          type: 'text',
          title: 'BBC Street Interviews: The future of news',
          titleAr: 'BBC: مقابلات الشارع - مستقبل الأخبار',
          paragraphs: [
            'The speakers talk about the types of news that interest them: celebrities, crime, culture, international news, local news, music, politics, sport and technology.',
            'Watch the video and tick the types of news that are mentioned. Then watch the second part and make notes on the predictions the speakers make about news in the future.',
          ],
        },
        {
          type: 'video',
          title: 'BBC Street Interviews: The future of news',
          titleAr: 'BBC: مقابلات الشارع - مستقبل الأخبار',
          videos: [
            {
              title: 'BBC Street Interviews: The future of news',
              file: 'SO3 B1 U5 BBC StreetInt.mp4',
              page: 64,
            },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u5-5d-predictions',
            title: 'Predictions from the interviews',
            kind: 'mcq',
            instructions: 'Choose the correct word to complete the summary for each speaker.',
            instructionsAr: 'اختر الكلمة الصحيحة لإكمال الملخص لكل متحدث.',
            page: 64,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'Isabelle: I think print media will ___ over time.',
                options: [
                  { label: 'disappear', correct: true },
                  { label: 'develop', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'Matt: There\u2019s too much ___ on the news.',
                options: [
                  { label: 'negativity', correct: true },
                  { label: 'positivity', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'Natalia: I think the ___ generation will be more interested in the news.',
                options: [
                  { label: 'younger', correct: true },
                  { label: 'older', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'Rob: Hopefully, people will stop getting their news from ___ media.',
                options: [
                  { label: 'social', correct: true },
                  { label: 'traditional', correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'Devante: Hopefully, it\u2019ll be a bit more ___ .',
                options: [
                  { label: 'selective', correct: true },
                  { label: 'interesting', correct: false },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'Ayesha: I definitely think that ___ are going to be more prominent in the news.',
                options: [
                  { label: 'influencers', correct: true },
                  { label: 'celebrities', correct: false },
                ],
              },
              {
                id: 'q7',
                kind: 'mcq',
                prompt: 'Henry: I think the news will be ___ a lot more.',
                options: [
                  { label: 'online', correct: true },
                  { label: 'offline', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'grammar',
          title: 'will, might and be going to for predictions',
          titleAr: 'will و might و be going to للتنبؤات',
          explanation:
            'We use will, might and be going to to talk about the future. Will shows strong certainty, might shows possibility, and be going to often shows a prediction based on present evidence or definite intention.',
          explanationAr:
            'نستخدم will و might و be going to للحديث عن المستقبل. تدل will على يقين قوي، وتدل might على احتمال، وكثيراً ما تدل be going to على توقع مبني على دليل حاضر أو نية مؤكدة.',
          rule: "will + verb = certain: 'I think print media will disappear.' might + verb = possible: 'I think it might be hard to distinguish real news from fake news.' be going to + verb = strong prediction: 'I definitely think that celebrities are going to be more prominent.'",
          ruleAr: "will + الفعل = مؤكد: 'I think print media will disappear.' might + الفعل = محتمل: 'I think it might be hard to distinguish real news from fake news.' be going to + الفعل = توقع قوي: 'I definitely think that celebrities are going to be more prominent.'",
          table: {
            headers: ['Modal', 'Strength of prediction', 'Example'],
            rows: [
              { values: ['will', 'strong/certain', 'I think print media will disappear.'] },
              { values: ['might', 'possible', 'I think it might be hard to distinguish real news from fake news.'] },
              { values: ['be going to', 'definite/predicted', 'I definitely think that celebrities are going to be more prominent.'] },
            ],
          },
          examples: [
            'I think print media will disappear.',
            'I think it might be hard to distinguish real news from fake news.',
            'I definitely think that celebrities are going to be more prominent.',
            'We will bring you wonderful stories from all around the world.',
            'We probably won\u2019t publish stories about disasters.',
          ],
          bankPage: 123,
          videos: [
            { id: 'WlT8fR9aWkY', title: 'How to Use Will, Would and Might - English Modal Verbs Lesson' },
            { id: '0anZBvnj6LM', title: 'Future in English - How to Talk about the Future' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u5-5d-will-might',
            title: 'will, might or be going to',
            kind: 'mcq',
            instructions: 'Complete the sentences from the interviews with the correct words.',
            instructionsAr: 'أكمل الجمل من المقابلات بالكلمات الصحيحة.',
            page: 65,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'Isabelle: I think print media ___ disappear.',
                options: [
                  { label: 'will', correct: true },
                  { label: 'might be', correct: false },
                  { label: 'going to be', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'I think it ___ hard to distinguish real news from fake news.',
                options: [
                  { label: 'might be', correct: true },
                  { label: 'will be going to', correct: false },
                  { label: 'going to', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'I definitely think that celebrities are ___ more prominent.',
                options: [
                  { label: 'going to be', correct: true },
                  { label: 'will', correct: false },
                  { label: 'might be going', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'Writing: a webpage about a news app',
          titleAr: 'الكتابة: صفحة ويب عن تطبيق أخبار',
          paragraphs: [
            'Read about the Happy News app. It brings you the best good news stories from around the world every day. "We will bring you wonderful stories about people from all around the world who are doing amazing things. We won\u2019t publish stories about disasters and political problems. By sharing these kinds of stories, we might start to make the world a better place."',
            'Write a webpage for your own news app. Include a description of the app, what it will include and won\u2019t include, and why people should subscribe.',
            'Key phrases: It will definitely have\u2026 It\u2019s going to\u2026 It probably won\u2019t have\u2026 Users will be able to\u2026 It might have\u2026 People will probably use it\u2026',
          ],
        },
        {
          type: 'pages',
          images: [img(78, 'Lesson 5D, page 64'), img(79, 'Lesson 5D, page 65')],
        },
      ],
    },
    {
      id: '5r',
      code: 'Review',
      title: 'Unit 5 Review',
      pages: [66, 66],
      blocks: [
        {
          type: 'text',
          title: 'Review what you have learned',
          titleAr: 'راجع ما تعلمته',
          paragraphs: [
            'Complete the review exercises to practise the grammar and vocabulary of Unit 5: relative clauses, reported speech, and will, might and be going to for predictions.',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u5-5r-definitions',
            title: 'Choose the correct words',
            kind: 'mcq',
            instructions: 'Choose the correct words to complete the definitions.',
            instructionsAr: 'اختر الكلمات الصحيحة لإكمال التعريفات.',
            page: 66,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'A person ___ plays in the same team as you.',
                options: [
                  { label: 'who', correct: true },
                  { label: 'when', correct: false },
                  { label: 'whose', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'The team ___ finishes top at the end of the season.',
                options: [
                  { label: 'that', correct: true },
                  { label: 'where', correct: false },
                  { label: 'when', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'The place ___ most of a university\u2019s buildings are located.',
                options: [
                  { label: 'where', correct: true },
                  { label: 'who', correct: false },
                  { label: 'whose', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'Someone ___ campaigns to create change in the world.',
                options: [
                  { label: 'who', correct: true },
                  { label: 'which', correct: false },
                  { label: 'when', correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'A process ___ involves taking old things and using them again.',
                options: [
                  { label: 'which', correct: true },
                  { label: 'when', correct: false },
                  { label: 'who', correct: false },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'To give money to help other people at a time ___ they need it.',
                options: [
                  { label: 'when', correct: true },
                  { label: 'who', correct: false },
                  { label: 'which', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u5-5r-future',
            title: 'Put the words in order',
            kind: 'ordering',
            instructions: 'Put the words in order to make sentences about the future.',
            instructionsAr: 'رتّب الكلمات بالترتيب الصحيح لتكوين جمل عن المستقبل.',
            page: 66,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'ordering',
                title: 'sentence 1',
                items: ['I', 'think', 'I\u2019ll', 'probably', 'do', 'a', 'different', 'job.'],
              },
              {
                id: 'q2',
                kind: 'ordering',
                title: 'sentence 2',
                items: ['I', 'might', 'retrain.'],
              },
              {
                id: 'q3',
                kind: 'ordering',
                title: 'sentence 3',
                items: ['I', 'probably', 'won\u2019t', 'move', 'house.'],
              },
              {
                id: 'q4',
                kind: 'ordering',
                title: 'sentence 4',
                items: ["I\u2019m", 'going', 'to', 'have', 'lots', 'of', 'children.'],
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Review listening',
          titleAr: 'استماع المراجعة',
          tracks: au(['R5.01'], 66),
        },
        {
          type: 'pages',
          images: [img(80, 'Unit 5 Review, page 66')],
        },
      ],
    },
  ],
}