import type { Unit } from '../../types/content'
import { au, img } from '../helpers'

export const unit04: Unit = {
  id: 'unit-4',
  number: 4,
  title: 'winners',
  phrase: 'talk about success, explain rules and describe memorable journeys',
  overviewPage: 43,
  pages: [43, 54],
  intro:
    'In this unit you talk about success and winning, use modals to give rules and advice, explain rules and procedures for a sport or game, and describe a memorable journey.',
  objectives: [
    '4A – understand a podcast about success; write an email/letter giving advice',
    '4B – read about famous technology firsts; talk about social media and websites',
    '4C – explain rules and procedures for a sport or game',
    '4D – understand a TV programme about a car race in Nepal; write a travel writing competition entry',
  ],
  video: [
    {
      title: 'BBC Vlogs: Have you ever won anything?',
      file: 'SO3 B1 U4 BBC Vlogs.mp4',
      page: 43,
    },
    {
      title: 'BBC Programmes: Top Gear: Nepal',
      file: 'SO3 B1 U4 BBC Programmes.mp4',
      page: 52,
    },
  ],
  lessons: [
    {
      id: '4a',
      code: '4A',
      title: 'Success',
      pages: [44, 46],
      labels: {
        grammar: 'modals for rules and advice',
        vocabulary: 'success',
        pronunciation: 'silent letters',
      },
      objectives: ['talk about success', 'use modals for rules and advice', 'write an email/letter giving advice'],
      blocks: [
        {
          type: 'text',
          title: 'How competitive are you?',
          titleAr: 'ما مدى حبّك للمنافسة؟',
          paragraphs: [
            'Do you always try to win? Do a questionnaire to find out. For each question, choose one answer which reflects your ideas.',
            'When I know that a task will be difficult, I try to forget about it and wait as long as possible before starting. Or I am very strict with myself and start the task as soon as possible. Or I think about it and prepare carefully before I start.',
            'Are you a bad loser who hates not winning? Do you try to understand what you did wrong and then try again, accept failure, or get angry or sad?',
            'When you win, do you have a party, treat yourself to something nice, or think nothing special about it?',
          ],
        },
        {
          type: 'vocab',
          title: 'success',
          titleAr: 'النجاح',
          items: [
            { word: 'talented', meaning: 'naturally good at something', meaningAr: 'موهوب', example: "She's a really talented dancer - she's so good!", exampleAr: 'إنها راقصة موهوبة حقاً - إنها بارعة جداً!' },
            { word: 'strict (with yourself)', meaning: 'demanding that rules are followed', meaningAr: 'صارم / متشدّد (مع نفسك)', example: 'He needs to be strict about when he starts work.', exampleAr: 'يحتاج أن يكون صارماً بشأن وقت بدئه للعمل.' },
            { word: 'do well', meaning: 'be successful', meaningAr: 'يُبلي بلاءً حسناً / ينجح', example: 'She is doing well at school and getting good grades.', exampleAr: 'إنها تبلي حسناً في المدرسة وتحصل على درجات جيدة.' },
            { word: 'bad loser', meaning: 'someone who reacts badly to losing', meaningAr: 'سيّئ في تقبّل الخسارة', example: "He hates it when his team doesn't win. He's a bad loser.", exampleAr: 'يكره عندما لا يفوز فريقه. إنه سيّئ في تقبّل الخسارة.' },
            { word: 'working hard', meaning: 'putting a lot of effort in', meaningAr: 'يعمل بجِدّ', example: "She's working hard, so I'm sure she'll be successful.", exampleAr: 'إنها تعمل بجِدّ، لذا أنا واثق أنها ستنجح.' },
            { word: 'competitive', meaning: 'always wanting to win', meaningAr: 'تنافسي / محبّ للمنافسة', example: 'The brothers are very competitive. They always want to win.', exampleAr: 'الأخوان تنافسيان جداً. يريدان الفوز دائماً.' },
            { word: 'carry on', meaning: 'continue', meaningAr: 'يستمر / يواصل', example: 'Carry on playing and do not stop until you win.', exampleAr: 'واصل اللعب ولا تتوقف حتى تفوز.' },
            { word: 'give up', meaning: 'stop trying', meaningAr: 'يستسلم / يتخلى عن', example: 'She is thinking about giving up her job.', exampleAr: 'إنها تفكر في التخلي عن وظيفتها.' },
            { word: 'failure', meaning: 'a person or thing that does not succeed', meaningAr: 'الفشل', example: 'Do not be afraid of failure.', exampleAr: 'لا تخف من الفشل.' },
            { word: 'succeed', meaning: 'achieve what you want', meaningAr: 'ينجح / يحقق ما يريد', example: 'Only a few people achieve their dreams.', exampleAr: 'قليلون فقط يحققون أحلامهم.' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4a-vocab',
            title: '4A Vocabulary',
            kind: 'fill-blank',
            instructions: 'Complete the sentences with the correct word from Lesson 4A.',
            instructionsAr: 'أكمل الجمل بالكلمة الصحيحة من الدرس 4A.',
            page: 44,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: "She's a really ___ dancer -",
                answer: 'talented',
                after: "she's so good!",
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'He needs to be',
                answer: 'strict',
                after: 'about when he starts work.',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: "She's",
                answer: 'doing well',
                after: 'at school and getting good grades.',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: "He hates it when his team doesn't win. He's a",
                answer: 'bad loser',
                after: '.',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: "She's",
                answer: 'working hard',
                after: "so I'm sure she'll be successful.",
              },
              {
                id: 'q6',
                kind: 'fill-blank',
                before: 'The brothers are very',
                answer: 'competitive',
                after: '. They always want to win.',
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'Podcast: Rules for success',
          titleAr: 'بودكاست: قواعد النجاح',
          paragraphs: [
            'We all have dreams - to play international football, become a senior manager in a company or write a best-selling book. Only a few people achieve their dreams. What do these winners share, and what can we learn from them?',
            'Track 4.01: listen to the podcast and number the main points in the order you hear them: work harder than other people; be friendly to the people you meet; decide what you want to achieve; take action \u2013 don\u2019t wait before you start; don\u2019t stop when you experience problems; relax and enjoy time off work.',
          ],
        },
        {
          type: 'audio',
          title: 'Podcast and pronunciation',
          titleAr: 'البودكاست والنطق',
          tracks: au(['4.01', '4.02'], 45),
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4a-podcast-tf',
            title: 'Podcast: True or False?',
            kind: 'true-false',
            instructions: 'Are the statements True (T) or False (F)? Listen to the podcast again and check.',
            instructionsAr: 'هل العبارات صحيحة (T) أم خاطئة (F)؟ استمع إلى البودكاست مرة أخرى وتحقق.',
            page: 45,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'true-false',
                statement: 'Novak Djokovic decided he wanted to win Wimbledon when he was young.',
                correct: true,
              },
              {
                id: 'q2',
                kind: 'true-false',
                statement: 'He made himself a Wimbledon trophy out of wood and metal.',
                correct: true,
              },
              {
                id: 'q3',
                kind: 'true-false',
                statement: 'The speakers agree that when you have a plan, you should start immediately.',
                correct: true,
              },
              {
                id: 'q4',
                kind: 'true-false',
                statement: 'The actor Will Smith thinks he is successful because he worked while other people slept.',
                correct: true,
              },
              {
                id: 'q5',
                kind: 'true-false',
                statement: 'Walt Disney had a boss who believed in his talent.',
                correct: false,
              },
              {
                id: 'q6',
                kind: 'true-false',
                statement: "The speakers agree that it's important to be nice to people if you want to be successful.",
                correct: true,
              },
            ],
          },
        },
        {
          type: 'grammar',
          title: 'modals for rules and advice',
          titleAr: 'الأفعال الناقصة للقواعد والنصائح',
          explanation:
            'Modal verbs change the meaning of the verb that follows. Some modals say something is necessary, some say it is not necessary, and some give advice.',
          explanationAr:
            'الأفعال الناقصة تغيّر معنى الفعل الذي يليها. بعضها يدل على أن شيئاً ضروري، وبعضها يدل على أنه غير ضروري، وبعضها يعطي نصيحة.',
          rule: "c = it is necessary. Have to / need to / must. a = it's a good idea: should. b = this isn't necessary: don't have to / needn't. d = don't do this, it isn't allowed or advised: mustn't.",
          ruleAr: "c = شيء ضروري. Have to / need to / must. a = فكرة جيدة: should. b = هذا ليس ضرورياً: don't have to / needn't. d = لا تفعل هذا، غير مسموح به أو يُنصح به: mustn't.",
          table: {
            headers: ['Modal', 'Meaning', 'Example'],
            rows: [
              { values: ['must / have to / need to', 'It is necessary. You have no choice.', "You must work really hard."] },
              { values: ["don't have to / needn't", "This isn't necessary.", "You needn't work all the time."] },
              { values: ['should / shouldn\u2019t', 'a good idea / a bad idea', 'You should be nice to people.'] },
              { values: ['mustn\u2019t', "Don't do this. It isn't allowed or advised.", "You mustn't give up."] },
            ],
          },
          examples: [
            'You need to set goals. You have to know what you want to achieve.',
            'You don\u2019t have to be more talented than everyone else, but you have to make more effort.',
            'You must work really hard and you mustn\u2019t give up.',
            'You should be nice to people, but you needn\u2019t work all the time.',
          ],
          bankPage: 116,
          videos: [
            { id: 'POFfLs0Uaio', title: 'Modal Verbs - How to Use Must, Have to and Should - English Grammar Lesson' },
            { id: '4GMU08J98MQ', title: 'Complete Guide to English Modal Verbs - English Grammar Lesson' },
            { id: 'oiIa2nAHkBw', title: 'How to Use Must in English - English Modal Verbs' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4a-modals',
            title: 'Rules for success',
            kind: 'mcq',
            instructions: 'Choose the correct modal verb.',
            instructionsAr: 'اختر الفعل الناقص الصحيح.',
            page: 45,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'You ___ set goals. You have to know what you want to achieve.',
                options: [
                  { label: 'need to', correct: true },
                  { label: 'mustn\u2019t', correct: false },
                  { label: 'needn\u2019t', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'You ___ be more talented than everyone else, but you have to make more effort.',
                options: [
                  { label: 'don\u2019t have to', correct: true },
                  { label: 'must', correct: false },
                  { label: 'have to', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'You ___ work really hard to achieve your dreams.',
                options: [
                  { label: 'must', correct: true },
                  { label: 'needn\u2019t', correct: false },
                  { label: 'don\u2019t have to', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'You ___ give up. Keep going!',
                options: [
                  { label: 'mustn\u2019t', correct: true },
                  { label: 'don\u2019t have to', correct: false },
                  { label: 'should', correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'You ___ be nice to people - it\u2019s a good idea.',
                options: [
                  { label: 'should', correct: true },
                  { label: 'mustn\u2019t', correct: false },
                  { label: 'have to', correct: false },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'You ___ work all the time - it\u2019s not necessary!',
                options: [
                  { label: 'needn\u2019t', correct: true },
                  { label: 'must', correct: false },
                  { label: 'have to', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'Writing: an email/letter giving advice',
          titleAr: 'كتابة: رسالة إلكترونية / رسالة لتقديم النصائح',
          paragraphs: [
            'Read the email from Marilyn to her friend Sara, who wants to change careers. The problem is that Sara hates working in an office. Marilyn gives advice: work out what you really want to do, do your research, try work experience or voluntary work, and think carefully before making a big change.',
            'Useful phrases for giving advice: you need to\u2026, try to think about\u2026, why not try\u2026, how about doing\u2026, make sure you\u2026, don\u2019t be afraid of\u2026, take the first small step.',
            'An informal email starts with a greeting like Hi Sara and ends with All the best.',
          ],
        },
        {
          type: 'pages',
          images: [img(58, 'Lesson 4A, page 44'), img(59, 'Lesson 4A, page 45'), img(60, 'Lesson 4A, page 46')],
        },
      ],
    },
    {
      id: '4b',
      code: '4B',
      title: 'First!',
      pages: [47, 49],
      labels: {
        grammar: 'articles',
        vocabulary: 'technology collocations; word building: suffixes',
        pronunciation: 'the',
      },
      objectives: ['read about famous technology firsts', 'use articles (a/an, the, no article)', 'talk about social media and websites'],
      blocks: [
        {
          type: 'text',
          title: 'First to fly',
          titleAr: 'أول من طار',
          paragraphs: [
            'Who made the first flight? Books about the history of flight often say it was the Wright brothers, but some people believe it was an inventor called Alberto Santos Dumont.',
            'On December 17, 1903, Orville and Wilbur Wright succeeded in getting their plane into the air for twelve seconds. Three years later, on October 23, 1906, Santos Dumont also flew. The Brazilian\u2019s flight was watched by hundreds of people as well as experts from the Aéro-Club de France.',
            'This was very different to the Wright brothers\u2019 flight, which hardly anyone saw. For this reason, many people in Europe didn\u2019t believe that the Wright brothers had really flown.',
          ],
        },
        {
          type: 'grammar',
          title: 'articles',
          titleAr: 'أدوات التعريف',
          explanation:
            'Articles tell the listener or reader if we are talking about something new, something already known, or things in general.',
          explanationAr:
            'أدوات التعريف تفيد المستمع أو القارئ هل نتحدث عن شيء جديد، أم شيء معروف، أم عن أشياء بشكل عام.',
          rule: "We use a/an the first time something is mentioned (new information) and with jobs. We use the when we know which person or thing we are talking about, and with superlatives. We use no article when we talk generally about people and things, and with most names of places.",
          ruleAr: 'نستخدم a/an عند ذكر الشيء لأول مرة (معلومة جديدة) ومع المهن. نستخدم the عندما نعرف الشخص أو الشيء الذي نتحدث عنه، ومع صيغ التفضيل. لا نستخدم أداة عندما نتحدث عن الناس والأشياء بشكل عام، ومع معظم أسماء الأماكن.',
          table: {
            headers: ['Article', 'Use', 'Example'],
            rows: [
              { values: ['a / an', 'first mention (new information)', 'Books often say it was the Wright brothers.'] },
              { values: ['a / an', 'jobs', 'He was an inventor.'] },
              { values: ['the', 'known person or thing', 'The Brazilian\u2019s flight was watched by hundreds of people.'] },
              { values: ['the', 'superlatives', 'the biggest questions'] },
              { values: ['no article', 'general people and things', 'Books about the history of flight'] },
              { values: ['no article', 'most names of places', 'France, North Carolina'] },
            ],
          },
          examples: [
            'Who made the first flight?',
            'He was an inventor called Alberto Santos Dumont.',
            'The first flight happened in a field in North Carolina, USA, or in France.',
            'The puzzle of who made the first flight remains one of the biggest questions in aeroplane history.',
          ],
          bankPage: 117,
          videos: [
            { id: '4ZufR8iYL7w', title: 'Articles in English - 5 Levels of Difficulty' },
            { id: 'r49hrj4cK5U', title: 'How to Use The - Articles in English Grammar' },
          ],
        },
        {
          type: 'audio',
          title: 'Pronunciation: the',
          titleAr: 'النطق: أداة the',
          tracks: au(['4.03'], 47),
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4b-articles',
            title: 'Articles: the joke',
            kind: 'fill-blank',
            instructions: 'Complete the joke by adding a / an, the or nothing (-).',
            instructionsAr: 'أكمل النكتة بإضافة a / an أو the أو لا شيء (-).',
            page: 54,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'A police officer stops ___ man driving',
                answer: 'a',
                after: 'a car.',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'He notices two penguins sitting on ___ back seat of',
                answer: 'the',
                after: 'the car.',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: "The man says, 'I found them. I like",
                answer: 'no article',
                accept: ['nothing', 'the'],
                after: "animals, so I put them in my car.'",
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: "The police officer says, 'Well, why don't you take them to ___ zoo?'",
                answer: 'the',
                after: "He drives away. The next day, the man drives past the same place.",
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'Famous Tech Firsts',
          titleAr: 'أول إنجازات التكنولوجيا الشهيرة',
          paragraphs: [
            '1839 - Frenchman Louis Daguerre invented the camera. But Robert Cornelius made changes to the invention and in 1839 tried an experiment using his own image. To take the picture, he sat still for fifteen minutes. The result was the very first selfie.',
            '1958 - William Higinbotham and Robert Dvorak created the world\u2019s first video game. It was a version of tennis. They developed the game to show to visitors at the Brookhaven National Laboratory, where they worked. Many years later, a similar game called Pong became famous.',
            '1973 - The first mobile phone call took place in 1973. Martin Cooper, an employee of the mobile phone company Motorola, made it. He made a call to a competitor and explained that he\u2019d won the race to invent the mobile phone. The invention weighed more than 1 kg and took ten hours to charge.',
            '1991 - The first webpage went live on 6 August, 1991. Tim Berners-Lee\u2019s invention showed how to create webpages! People read it to find information that eventually changed the world.',
            '1992 - The first text message appeared on 3 December, 1992. Neil Papworth, working on SMS for Vodaphone, sent the message \u2018Merry Christmas\u2019. Now about 5 billion people send and receive texts.',
            '2005 - The first YouTube video appeared on 23 April, 2005. It was called \u2018meet me at the zoo\u2019 and it consisted of eighteen seconds of a boy talking about elephants!',
            '2006 - The first tweet appeared at 12.50 p.m. PST on 21 March, 2006, sent by the co-founder of Twitter, Jack Dorsey. It read \u2018just setting up my twttr\u2019.',
            '2010 - The first Instagram post was a photo of a dog next to a woman\u2019s foot. The photo was taken by the co-founder of Instagram, Kevin Systrom, on 16 July, 2010.',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4b-firsts-mcq',
            title: 'When was the first\u2026?',
            kind: 'mcq',
            instructions: 'Choose the correct date for each technology first.',
            instructionsAr: 'اختر التاريخ الصحيح لكل إنجاز تكنولوجي أول.',
            page: 48,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'The first webpage went live in\u2026',
                options: [
                  { label: '1991', correct: true },
                  { label: '1981', correct: false },
                  { label: '2001', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'The first video game was created in\u2026',
                options: [
                  { label: '1958', correct: true },
                  { label: '1978', correct: false },
                  { label: '1998', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'The first YouTube video appeared in\u2026',
                options: [
                  { label: '2005', correct: true },
                  { label: '1995', correct: false },
                  { label: '2000', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'The first Instagram post was in\u2026',
                options: [
                  { label: '2010', correct: true },
                  { label: '1990', correct: false },
                  { label: '2000', correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'The first mobile phone call was made in\u2026',
                options: [
                  { label: '1973', correct: true },
                  { label: '1999', correct: false },
                  { label: '2010', correct: false },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'The first selfie was taken in\u2026',
                options: [
                  { label: '1839', correct: true },
                  { label: '1950', correct: false },
                  { label: '1989', correct: false },
                ],
              },
              {
                id: 'q7',
                kind: 'mcq',
                prompt: 'The first text message was sent in\u2026',
                options: [
                  { label: '1992', correct: true },
                  { label: '1982', correct: false },
                  { label: '2002', correct: false },
                ],
              },
              {
                id: 'q8',
                kind: 'mcq',
                prompt: 'The first tweet was sent in\u2026',
                options: [
                  { label: '2006', correct: true },
                  { label: '1996', correct: false },
                  { label: '2016', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'vocab',
          title: 'technology collocations; word building: suffixes',
          titleAr: 'تراكيب التكنولوجيا؛ بناء الكلمات: اللواحق',
          items: [
            { word: 'create a webpage', meaningAr: 'ينشئ صفحة ويب', example: 'Tim Berners-Lee showed how to create webpages.', exampleAr: 'أوضح تيم بيرنرز-لي كيفية إنشاء صفحات الويب.' },
            { word: 'send / receive a text', meaningAr: 'يرسل / يستقبل رسالة نصية', example: 'Didn\u2019t you receive all my texts?', exampleAr: 'ألم تستقبل كل رسائلي النصية؟' },
            { word: 'download an app', meaningAr: 'يحمّل تطبيقاً', example: 'You just use your email address and add a password.', exampleAr: 'كل ما عليك هو استخدام بريدك الإلكتروني وإضافة كلمة مرور.' },
            { word: 'launch a website', meaningAr: 'يُطلق موقعاً إلكترونياً', example: 'When we launched a website last year, we didn\u2019t expect so many people to visit it so quickly!', exampleAr: 'عندما أطلقنا موقعاً إلكترونياً العام الماضي، لم نتوقع أن يزوره الكثيرون بهذه السرعة!' },
            { word: 'post a photo', meaningAr: 'ينشر صورة', example: 'Do you post photos on social media?', exampleAr: 'هل تنشر صوراً على وسائل التواصل الاجتماعي؟' },
            { word: 'share a video or photo', meaningAr: 'يشارك مقطع فيديو أو صورة', example: 'I shared a video with my friends on Instagram.', exampleAr: 'شاركت مقطع فيديو مع أصدقائي على إنستغرام.' },
            { word: 'comment on a webpage', meaningAr: 'يعلّق على صفحة ويب', example: 'Please leave a comment on their website.', exampleAr: 'من فضلك اترك تعليقاً على موقعهم الإلكتروني.' },
            { word: 'go viral', meaningAr: 'ينتشر بسرعة (فيروسياً)', example: 'It didn\u2019t exactly go viral, but it did launch a website that has been incredibly popular.', exampleAr: 'لم ينتشر بشكل واسع، لكنه أطلق موقعاً إلكترونياً حظي بشعبية هائلة.' },
          ],
          source: 'See also Vocabulary Bank, page 139',
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4b-suffixes',
            title: 'Word building: suffixes',
            kind: 'mcq',
            instructions: 'Match each verb with its related noun (look at the text again to help you).',
            instructionsAr: 'طابق كل فعل مع الاسم المرتبط به (أعد النظر إلى النص لمساعدتك).',
            page: 49,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'What is the noun form of "invent"?',
                options: [
                  { label: 'invention', correct: true },
                  { label: 'employer / employee' },
                  { label: 'competition' },
                  { label: 'manager' },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'What is the noun form of "employ"?',
                options: [
                  { label: 'invention' },
                  { label: 'employer / employee', correct: true },
                  { label: 'competition' },
                  { label: 'manager' },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'What is the noun form of "compete"?',
                options: [
                  { label: 'invention' },
                  { label: 'employer / employee' },
                  { label: 'competition', correct: true },
                  { label: 'manager' },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'What is the noun form of "manage"?',
                options: [
                  { label: 'invention' },
                  { label: 'employer / employee' },
                  { label: 'competition' },
                  { label: 'manager', correct: true },
                ],
              },
            ],
          },
        },
        {
          type: 'pages',
          images: [img(61, 'Lesson 4B, page 47'), img(62, 'Lesson 4B, page 48'), img(63, 'Lesson 4B, page 49')],
        },
      ],
    },
    {
      id: '4c',
      code: '4C',
      title: 'Taking part',
      pages: [50, 51],
      labels: {
        grammar: 'How to\u2026 explain rules and procedures',
        vocabulary: 'sports and games',
        pronunciation: "can and can't",
      },
      objectives: ['explain rules and procedures for a sport or game', 'talk about sports and games'],
      blocks: [
        {
          type: 'text',
          title: 'Is it a sport?',
          titleAr: 'هل هي رياضة؟',
          paragraphs: [
            'Can we call board games like chess a sport? If you are really good at computer games and take part in e-sports competitions, are you a sportsperson? Some people would call these activities games rather than sports, but not everyone agrees.',
            "What makes a sport? First, it's an activity that requires physical skill and fitness. Secondly, it has a set of rules. And lastly, you can play it competitively, so there's a result, along with a winner and loser. Chess and e-sports certainly have rules and are competitive. What do you think? What about bowling, dance and fishing? Are they sports, or just hobbies?",
          ],
        },
        {
          type: 'vocab',
          title: 'sports and games',
          titleAr: 'الرياضات والألعاب',
          items: [
            { word: 'take part in', meaning: 'participate in', meaningAr: 'يشارك في', example: 'Do you take part in any sports?', exampleAr: 'هل تشارك في أي رياضة؟' },
            { word: 'support a team', meaning: 'want a team to win', meaningAr: 'يشجّع فريقاً', example: 'I support Manchester United.', exampleAr: 'أنا أشجّع مانشستر يونايتد.' },
            { word: 'a fan of a team/player', meaning: 'enjoy watching them', meaningAr: 'مشجّع لفريق/لاعب', example: 'Are you a fan of any teams or players?', exampleAr: 'هل أنت مشجّع لأي فريق أو لاعب؟' },
            { word: 'a champion', meaning: 'the winner of a competition', meaningAr: 'البطل / الفائز بالبطولة', example: "We're the champions!", exampleAr: 'نحن الأبطال!' },
            { word: 'score points / goals', meaning: 'get points in a game', meaningAr: 'يسجّل نقاطاً / أهدافاً', example: 'Do you know how you score points?', exampleAr: 'هل تعرف كيف تسجّل النقاط؟' },
            { word: 'board game', meaning: 'a game played on a board', meaningAr: 'لعبة لوحية', example: 'Do you have any board games at home?', exampleAr: 'هل لديك أي ألعاب لوحية في المنزل؟' },
            { word: 'e-sports', meaning: 'competitive video gaming', meaningAr: 'الرياضات الإلكترونية', example: 'He takes part in e-sports competitions.', exampleAr: 'إنه يشارك في مسابقات الرياضات الإلكترونية.' },
          ],
        },
        {
          type: 'audio',
          title: 'How to play floorball',
          titleAr: 'كيف تلعب الفلوربول',
          tracks: au(['4.04'], 51),
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4c-floorball',
            title: 'Floorball: True or False?',
            kind: 'true-false',
            instructions: 'Listen to a game called floorball and decide if the statements are True (T) or False (F).',
            instructionsAr: 'استمع إلى لعبة اسمها فلوربول وحدّد هل العبارات صحيحة (T) أم خاطئة (F).',
            page: 51,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'true-false',
                statement: 'Floorball is an outdoor sport.',
                correct: false,
              },
              {
                id: 'q2',
                kind: 'true-false',
                statement: "You can't score goals in floorball.",
                correct: false,
              },
              {
                id: 'q3',
                kind: 'true-false',
                statement: 'There are six players in each team.',
                correct: false,
              },
              {
                id: 'q4',
                kind: 'true-false',
                statement: 'All of the players use a stick.',
                correct: true,
              },
              {
                id: 'q5',
                kind: 'true-false',
                statement: "The game starts with a 'face-off'.",
                correct: true,
              },
              {
                id: 'q6',
                kind: 'true-false',
                statement: 'A match takes one hour and twenty minutes.',
                correct: false,
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Pronunciation: can and can\u2019t',
          titleAr: 'النطق: can و can\u2019t',
          tracks: au(['4.05'], 51),
        },
        {
          type: 'grammar',
          title: 'How to\u2026 explain rules and procedures',
          titleAr: 'كيف نشرح القواعد والإجراءات',
          explanation:
            'When we explain rules and procedures, we present the information in a clear sequence with a clear structure, starting with more general information and then adding more details.',
          explanationAr:
            'عندما نشرح القواعد والإجراءات، نقدم المعلومات في تسلسل واضح وبنية واضحة، نبدأ بمعلومات عامة ثم نضيف تفاصيل أكثر.',
          rule: "Start with the aim: The aim of the game is to\u2026 Then say how it is organised: There are (six players). It is played on a field. Then the procedure: To start with\u2026 Then / Next\u2026 After that\u2026 . Then the rules: You score (shooting the ball into the goal). You can\u2026 You have to / must\u2026 You can't / mustn't\u2026 It lasts (one hour).",
          ruleAr: 'ابدأ بالهدف: The aim of the game is to\u2026 ثم قل كيف تُنظَّم اللعبة: There are (six players). It is played on a field. ثم الإجراء: To start with\u2026 Then / Next\u2026 After that\u2026 ثم القواعد: You score (shooting the ball into the goal). You can\u2026 You have to / must\u2026 You can\u2019t / mustn\u2019t\u2026 وتستمر اللعبة: It lasts (one hour).',
          table: {
            headers: ['Information', 'Language'],
            rows: [
              { values: ['how to win', 'The goal is to\u2026 / The aim of the game is to\u2026'] },
              { values: ['organisation and equipment', 'There are (six players). It is played on a field.'] },
              { values: ['procedure', 'To start with\u2026 Then / Next\u2026 After that\u2026'] },
              { values: ['rules', "You score (shooting the ball into the goal). You can\u2026 You have to / must\u2026 You can't / mustn't\u2026"] },
            ],
          },
          examples: [
            'That was the first time I have ever played floorball.',
            'Let us know in the comments - are bowling, dance and fishing sports, or just hobbies?',
            'The aim of the game is to score more goals than the other team.',
          ],
          bankPage: 118,
          videos: [
            { id: '4GMU08J98MQ', title: 'Complete Guide to English Modal Verbs - English Grammar Lesson' },
            { id: 'rrSl1bQcnoI', title: 'Using the Verb Be - 5 Levels of English Grammar' },
            { id: 'POFfLs0Uaio', title: 'Modal Verbs - How to Use Must, Have to and Should - English Grammar Lesson' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4c-rules',
            title: 'Rules and procedures',
            kind: 'fill-blank',
            instructions: 'Complete the phrases using the words in the box (can\u2019t, first, lasts, by, aim).',
            instructionsAr: 'أكمل العبارات باستخدام الكلمات الموجودة في الصندوق (can\u2019t، first، lasts، by، aim).',
            page: 51,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'The',
                answer: 'aim',
                after: 'of the game is to score more goals.',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'It is played',
                answer: 'first',
                accept: ['on'],
                after: 'on a field. (OC: complete with the correct word)',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: 'It',
                answer: 'lasts',
                after: 'one hour.',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'You score',
                answer: 'by',
                after: 'shooting the ball into the goal.',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: 'You',
                answer: 'can\u2019t',
                after: 'hit the ball with your hands.',
              },
            ],
          },
        },
        {
          type: 'pages',
          images: [img(64, 'Lesson 4C, page 50'), img(65, 'Lesson 4C, page 51')],
        },
      ],
    },
    {
      id: '4d',
      code: '4D',
      title: 'Top Gear: Nepal',
      pages: [52, 53],
      labels: {
        grammar: 'present perfect + superlative',
        skills: 'talk about a memorable journey',
      },
      objectives: ['understand a TV programme about a car race in Nepal', 'use the present perfect + superlative', 'write a travel writing competition entry'],
      blocks: [
        {
          type: 'text',
          title: 'BBC Programmes: Top Gear: Nepal',
          titleAr: 'برامج BBC: توب جير: نيبال',
          paragraphs: [
            'Top Gear is the BBC\u2019s international award-winning television series about cars. On the show, the three presenters compare and test-drive cars, and organise all kinds of crazy races.',
            'In this episode, the presenters are in Kathmandu, the capital of Nepal. They are racing to get to a city called Lo Manthang, but it\u2019s a difficult drive with lots of traffic, mountains and rivers to cross!',
          ],
        },
        {
          type: 'video',
          title: 'Watch and order the events',
          titleAr: 'شاهد ورتّب الأحداث',
          videos: [
            {
              title: 'BBC Programmes: Top Gear: Nepal',
              file: 'SO3 B1 U4 BBC Programmes.mp4',
              page: 52,
            },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4d-order',
            title: 'Number the events in order',
            kind: 'ordering',
            instructions: 'Watch the video and put the presenters\u2019 actions in the correct order.',
            instructionsAr: 'شاهد الفيديو وضع تصرفات المقدمين بالترتيب الصحيح.',
            page: 52,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'ordering',
                title: 'Events in the video',
                items: [
                  'receive their instructions on a piece of paper',
                  'drive out of Kathmandu',
                  'drive along the side of a mountain',
                  'drive across a river',
                  'camp for the night',
                  'leave the blue Renault 4 car by the side of the road',
                  'arrive at the \u2018Forbidden City\u2019 of Lo Manthang',
                ],
              },
            ],
          },
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4d-video-tf',
            title: 'Watch again: True or False?',
            kind: 'true-false',
            instructions: 'Are the statements True (T) or False (F)? Watch again and check.',
            instructionsAr: 'هل العبارات صحيحة (T) أم خاطئة (F)؟ شاهد مرة أخرى وتحقق.',
            page: 52,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'true-false',
                statement: 'The presenters find it easy to drive out of Kathmandu.',
                correct: false,
              },
              {
                id: 'q2',
                kind: 'true-false',
                statement: 'Outside Kathmandu the roads are bumpy.',
                correct: true,
              },
              {
                id: 'q3',
                kind: 'true-false',
                statement: 'One presenter asks for help because his car gets stuck in the water.',
                correct: true,
              },
              {
                id: 'q4',
                kind: 'true-false',
                statement: 'One presenter says that driving on the mountain is frightening.',
                correct: true,
              },
              {
                id: 'q5',
                kind: 'true-false',
                statement: 'They leave the blue car on the side of the road after ten days.',
                correct: false,
              },
              {
                id: 'q6',
                kind: 'true-false',
                statement: 'The red car is the winner.',
                correct: true,
              },
            ],
          },
        },
        {
          type: 'grammar',
          title: 'present perfect + superlative',
          titleAr: 'المضارع التام + صيغة التفضيل',
          explanation:
            'We can use the present perfect + the superlative form of an adjective to talk about an experience related to our whole life.',
          explanationAr:
            'يمكننا استخدام المضارع التام + صيغة التفضيل للصفة للحديث عن تجربة لها علاقة بحياتنا كلها.',
          rule: "Subject + has/have + the superlative adjective + I've ever + past participle. Example: 'This is the worst\u2026 I've ever seen!'",
          ruleAr: 'الفاعل + has/have + صيغة التفضيل للصفة + I\u2019ve ever + التصريف الثالث. مثال: "This is the worst\u2026 I\u2019ve ever seen!" أي: هذا أسوأ ما رأيته في حياتي!',
          table: {
            headers: ['Pattern', 'Example'],
            rows: [
              { values: ['This is the best + noun + I\u2019ve ever + past participle', "This is the best holiday I've ever had!"] },
              { values: ["It's the worst + noun + I've ever + past participle", "It's the worst hotel I've ever stayed in."] },
              { values: ["It's the longest + noun + I've ever + past participle", "It's the longest journey I've been on!"] },
            ],
          },
          examples: [
            "This is the worst\u2026 I've ever seen!",
            "It's the worst hotel I've ever stayed in.",
            "It's the longest journey I've been on!",
          ],
          bankPage: 119,
          videos: [
            { id: 'zBzUJlOo930', title: 'Present Perfect Verb Tense - English Grammar Lesson' },
            { id: 'wC5GPzMb9BE', title: 'How to Use Adjectives in English - English Grammar Course' },
            { id: 'UlNuPWiyK9Y', title: 'Adjectives and Adverbs in English - 5 Levels of Difficulty' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4d-superlative',
            title: 'The present perfect + superlative',
            kind: 'fill-blank',
            instructions: 'Complete the sentences with the correct form of the words in brackets. Use the present perfect and a superlative.',
            instructionsAr: 'أكمل الجمل بالصيغة الصحيحة للكلمات بين الأقواس. استخدم المضارع التام وصيغة التفضيل.',
            page: 54,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: "It's the most interesting book",
                answer: "I've ever read",
                after: '. (interesting/read)',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'That was',
                answer: 'the best pizza I\u2019ve ever eaten',
                after: '! (good/eat)',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: 'This is',
                answer: 'the worst hotel I\u2019ve ever stayed in',
                after: '! (bad/stay)',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'Venice is',
                answer: 'the most amazing city I\u2019ve ever visited',
                after: '! (amazing/visit)',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: "She's",
                answer: 'the funniest person I\u2019ve ever met',
                after: '. (funny/meet)',
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'Talk about a memorable journey',
          titleAr: 'تحدث عن رحلة لا تُنسى',
          paragraphs: [
            'Listen to someone talking about a memorable journey and answer the questions: Where did she go, and who with? How did they travel? What did they see? Why did they have to stay in a town for a few days?',
          ],
        },
        {
          type: 'audio',
          title: 'Listening: a memorable journey',
          titleAr: 'استماع: رحلة لا تُنسى',
          tracks: au(['4.06'], 53),
        },
        {
          type: 'vocab',
          title: 'Key phrases: a memorable journey',
          titleAr: 'عبارات أساسية: رحلة لا تُنسى',
          items: [
            { word: '', meaning: '', example: "The most memorable journey I've ever been on was\u2026", exampleAr: 'أكثر رحلة لا تُنسى سافرت فيها كانت…' },
            { word: '', meaning: '', example: "It was my first time\u2026", exampleAr: 'كانت أول مرة لي…' },
            { word: '', meaning: '', example: "It was one of the most amazing\u2026", exampleAr: 'كانت واحدة من أكثر … إثارة للإعجاب' },
            { word: '', meaning: '', example: "It was memorable because\u2026", exampleAr: 'كانت لا تُنسى لأن…' },
            { word: '', meaning: '', example: "The journey took\u2026 days.", exampleAr: 'استغرقت الرحلة … أيام.' },
            { word: '', meaning: '', example: "\u2026 is definitely the most interesting place I've been to.", exampleAr: '… هو بالتأكيد أكثر مكان مثير للاهتمام زرته.' },
          ],
        },
        {
          type: 'text',
          title: 'Writing: a travel writing competition entry',
          titleAr: 'كتابة: مشاركة في مسابقة كتابة عن السفر',
          paragraphs: [
            'Tell us about a difficult journey. Where were you going? Who with? What happened and why was it difficult? What happened in the end? We accept stories about all kinds of journeys: road trips, train trips, car journeys, hikes, flights, etc. The winner wins an all-expenses trip to a Caribbean island!',
            'Model answer: Car trouble in the Big Easy. "The most difficult car ride I\u2019ve ever had was in my friend Ricky\u2019s 1959 Buick Roadmaster in New Orleans." Ricky and the writer were trying to find a jazz club, got lost, ran out of gas, and never found the club - but they did find a great restaurant which sold the best seafood sandwiches ever.',
            'Write 100-140 words and include as many interesting details as you can.',
          ],
        },
        {
          type: 'pages',
          images: [img(66, 'Lesson 4D, page 52'), img(67, 'Lesson 4D, page 53')],
        },
      ],
    },
    {
      id: '4r',
      code: 'Review',
      title: 'Unit 4 Review',
      pages: [54, 54],
      blocks: [
        {
          type: 'text',
          title: 'Review what you have learned',
          titleAr: 'راجع ما تعلمته',
          paragraphs: [
            'Complete the review exercises to practise the grammar and vocabulary of Unit 4: modals for rules and advice (six tips for how to live a happier life), articles (the joke about the penguins), and the present perfect + superlative.',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u4-4r-modals',
            title: 'Six tips for a happier life',
            kind: 'mcq',
            instructions: 'Choose the correct words to complete the tips.',
            instructionsAr: 'اختر الكلمات الصحيحة لإكمال النصائح.',
            page: 54,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'You ___ try to spend some time enjoying nature each day. It reduces stress.',
                options: [
                  { label: 'should', correct: true },
                  { label: "don't have to", correct: false },
                  { label: "mustn't", correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: "You ___ run a marathon, but a small amount of exercise will make you feel better.",
                options: [
                  { label: "need to", correct: false },
                  { label: "don't need to", correct: true },
                  { label: "mustn't", correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: "You ___ spend too much time alone.",
                options: [
                  { label: "mustn't", correct: true },
                  { label: "need to", correct: false },
                  { label: "must", correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'You ___ get enough sleep. Most people need to sleep for between six and eight hours.',
                options: [
                  { label: 'should', correct: true },
                  { label: "mustn't", correct: false },
                  { label: "needn't", correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'Your brain needs to be challenged. You ___ be really talented, but learning a new skill can be fun.',
                options: [
                  { label: 'don\u2019t have to', correct: true },
                  { label: 'have to', correct: false },
                  { label: 'must', correct: false },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'You ___ laugh as much as possible. Humour can help you get through difficult times.',
                options: [
                  { label: 'should', correct: true },
                  { label: "mustn't", correct: false },
                  { label: "shouldn't", correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Review listenings',
          titleAr: 'استماعات المراجعة',
          tracks: au(['R4.01', 'R4.02'], 54),
        },
        {
          type: 'pages',
          images: [img(68, 'Unit 4 Review, page 54')],
        },
      ],
    },
  ],
}