import type { Unit } from '../../types/content'
import { au, img } from '../helpers'

export const unit07: Unit = {
  id: 'unit-7',
  number: 7,
  title: 'travel',
  phrase: 'talk about travel, new experiences and making recommendations',
  overviewPage: 79,
  pages: [79, 90],
  intro:
    'In this unit you read about how to be a better tourist, listen to someone who moved abroad, make and respond to recommendations, and discuss why we travel.',
  objectives: [
    '7A – read an article about responsible tourism; talk about tourism',
    '7B – understand someone talking about moving abroad; write a description of an experience',
    '7C – make and respond to recommendations',
    '7D – understand people talking about travelling; write an essay about why we travel',
  ],
  video: [
    {
      title: 'BBC Vlogs: Where do you feel happiest?',
      file: 'SO3 B1 U7 BBC Vlogs.mp4',
      page: 79,
    },
    {
      title: 'BBC Street Interviews: Go solo?',
      file: 'SO3 B1 U7 BBC StreetInt.mp4',
      page: 88,
    },
  ],
  lessons: [
    {
      id: '7a',
      code: '7A',
      title: 'Good tourists',
      pages: [80, 82],
      labels: {
        grammar: 'first and second conditionals',
        vocabulary: 'travel and tourism',
        pronunciation: 'contractions',
      },
      objectives: ['read an article about responsible tourism', 'use the first and second conditionals', 'talk about tourism'],
      blocks: [
        {
          type: 'text',
          title: 'Be a better tourist',
          titleAr: 'كن سائحاً أفضل',
          paragraphs: [
            'There are traffic jams at Machu Picchu, in Peru, and more than 30 million tourists visit the city of Venice every year. We all love travelling, but we have to accept that people also live in the places we visit. To make their lives easier, here are some tips you can follow.',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u7-7a-headings',
            title: 'Put the headings in the right places',
            kind: 'ordering',
            instructions: 'Read the article and place the headings in the correct order: See more than just the key sights; Try somewhere different; Say something!; Be respectful; Keep it clean; Time your trip carefully.',
            instructionsAr: 'اقرأ المقال وضع العناوين في الترتيب الصحيح.',
            page: 80,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'ordering',
                title: 'Headings for the article',
                items: [
                  'Try somewhere different',
                  'Time your trip carefully',
                  'See more than just the key sights',
                  'Say something! (learn a few words of the local language)',
                  'Be respectful (understand local customs)',
                  'Keep it clean',
                ],
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'The article: responsible tourism',
          titleAr: 'المقال: السياحة المسؤولة',
          paragraphs: [
            'Why go to the same place as everyone else? Instead of going to the most popular festivals, you could try alternative destinations. For example, instead of going to Venice to see its famous carnival, you could try Annecy, in France, where they recreate the magic of the Venetian carnival, but without the crowds. If people tried going somewhere different, the main tourist destinations wouldn\u2019t be so busy.',
            'If possible, travel out of season, so that popular places don\u2019t become too crowded. If you plan a trip to Prague, why not spend a week there rather than just two days? Use the time to really get to know the city. When you visit Amsterdam, you can use a special app that sends notifications to your phone if part of the city is busier than usual. This way you can help avoid making long queues at museums.',
            'If you go to Paris, you\u2019ll probably want to go sightseeing. Visit the Eiffel Tower and the Louvre, but don\u2019t just stop at the main tourist attractions. Travel to the edges of the city and see what you can discover there. You will have special memories of a city if you discover some local places for yourself.',
            'Be respectful. If you travel to somewhere new, you\u2019ll understand the culture better if you read a book about its history, or read a novel by a local author. Customs differ around the world and it\u2019s important to understand and respect local customs and traditions. You need to watch your body language. Is it polite to shake hands when you meet someone for the first time, or should you bow your head? If you get these customs wrong, you can easily offend people.',
            'Say something! Try to learn a few of the most common words or phrases. Hello, excuse me, thank you and goodbye are all essential. If you try to speak their language, people will appreciate your efforts.',
            'Keep it clean. Don\u2019t leave a mess wherever you go. From the beaches of Goa to the streets of London, plastic waste is a huge problem for the environment. If everyone took their litter home with them, tourist destinations would be a lot cleaner and more attractive. Remember the saying: "Take only memories, leave only footprints."',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u7-7a-reading',
            title: 'The article: comprehension',
            kind: 'mcq',
            instructions: 'Answer the questions about the article.',
            instructionsAr: 'أجب عن الأسئلة حول المقال.',
            page: 80,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'What is the problem at Machu Picchu?',
                options: [
                  { label: 'There are traffic jams.', correct: true },
                  { label: 'The site is closed.', correct: false },
                  { label: 'It is too expensive.', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'How can you avoid going to places that are very crowded?',
                options: [
                  { label: 'Travel out of season.', correct: true },
                  { label: 'Visit only museums.', correct: false },
                  { label: 'Go in August.', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'Why should you try to learn a few words of the local language?',
                options: [
                  { label: 'People will appreciate your efforts.', correct: true },
                  { label: 'You will offend people otherwise.', correct: false },
                  { label: 'It is compulsory.', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'What should tourists take from a destination?',
                options: [
                  { label: 'Only memories.', correct: true },
                  { label: 'Litter.', correct: false },
                  { label: 'Plants.', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'vocab',
          title: 'travel and tourism',
          titleAr: 'السفر والسياحة',
          items: [
            { word: 'tradition / traditional', meaning: 'a custom passed on through generations', meaningAr: 'التقليد / تقليدي', example: 'It\u2019s a local tradition in Poland for people to throw water at each other on \u2018wet Monday\u2019.', exampleAr: 'إنه تقليد محلي في بولندا أن يرشّ الناس الماء على بعضهم في «الاثنين المبلل».' },
            { word: 'custom', meaning: 'usual behaviour in a place', meaningAr: 'العادة / التقليد', example: 'Family life is very important in Italian customs.', exampleAr: 'الحياة الأسرية مهمة جداً في العادات الإيطالية.' },
            { word: 'out of season', meaning: 'when there are not so many tourists', meaningAr: 'خارج الموسم', example: 'You can usually find much better prices if you travel out of season.', exampleAr: 'عادة ما تجد أسعاراً أفضل بكثير إذا سافرت خارج الموسم.' },
            { word: 'festival', meaning: 'a special day or period of celebration', meaningAr: 'مهرجان / عيد', example: 'Chinese New Year is one of China\u2019s most important festivals.', exampleAr: 'رأس السنة الصينية من أهم المهرجانات في الصين.' },
            { word: 'tourist destination', meaning: 'a place where tourists go', meaningAr: 'وجهة سياحية', example: 'The USA, Spain and Japan are three of the most popular tourist destinations.', exampleAr: 'الولايات المتحدة وإسبانيا واليابان من أكثر الوجهات السياحية شعبية.' },
            { word: 'weekend trip / break', meaning: 'a short trip', meaningAr: 'رحلة نهاية الأسبوع / إجازة قصيرة', example: "We're going for a short break to the Lake District this weekend.", exampleAr: 'سنذهب في إجازة قصيرة إلى منطقة ليك ديستريكت هذا الأسبوع.' },
            { word: 'go sightseeing', meaning: 'visit the famous places', meaningAr: 'يتجول لمشاهدة المعالم', example: 'We saw all the main sights yesterday.', exampleAr: 'شاهدنا كل المعالم الرئيسية أمس.' },
            { word: 'queue', meaning: 'a line of people waiting', meaningAr: 'طابور / صف منتظرين', example: 'I hate standing in queues with all those people.', exampleAr: 'أكره الوقوف في الطوابير مع كل هؤلاء الناس.' },
            { word: 'traffic jams', meaning: 'long lines of slow traffic', meaningAr: 'الازدحامات المرورية', example: 'There are often traffic jams on the way to the beach.', exampleAr: 'غالباً ما تكون هناك ازدحامات مرورية في الطريق إلى الشاطئ.' },
            { word: 'attractions', meaning: 'interesting places to visit', meaningAr: 'المعالم / أماكن الجذب', example: 'Which attractions do you visit?', exampleAr: 'أي معالم تزور؟' },
            { word: 'trip', meaning: 'a journey to a place and back again', meaningAr: 'رحلة', example: 'We\u2019re going on a trip to the Lake District.', exampleAr: 'سنقوم برحلة إلى منطقة ليك ديستريكت.' },
          ],
          source: 'See also Vocabulary Bank, page 142 (travel and tourism)',
        },
        {
          type: 'grammar',
          title: 'first and second conditionals',
          titleAr: 'الجمل الشرطية من النوع الأول والثاني',
          explanation:
            'The first conditional describes a real, possible situation in the future. The second conditional describes a hypothetical or imaginary situation.',
          explanationAr:
            'تصف الجملة الشرطية من النوع الأول موقفاً حقيقياً ومحتملاً في المستقبل. وتصف الجملة الشرطية من النوع الثاني موقفاً افتراضياً أو متخيلاً.',
          rule: "First conditional: If + present simple + will (If you travel to somewhere new, you'll understand the culture better.) Second conditional: If + past simple + would (If everyone took their litter home with them, tourist destinations would be a lot cleaner.)",
          ruleAr: "الجملة الشرطية الأولى: If + المضارع البسيط + will (If you travel to somewhere new, you'll understand the culture better.) الجملة الشرطية الثانية: If + الماضي البسيط + would (If everyone took their litter home with them, tourist destinations would be a lot cleaner.)",
          table: {
            headers: ['Conditional', 'Form', 'Use', 'Example'],
            rows: [
              { values: ['first', 'If + present simple + will', 'real, possible future', "If you try to speak their language, people will appreciate your efforts."] },
              { values: ['second', 'If + past simple + would', 'hypothetical, not real', "If people tried going somewhere different, the main tourist destinations wouldn't be so busy."] },
            ],
          },
          examples: [
            "If you travel to somewhere new, you'll understand the culture better if you read a book about its history.",
            'If you try to speak their language, people will appreciate your efforts.',
            "If people tried going somewhere different, the main tourist destinations wouldn't be so busy.",
            "If everyone took their litter home with them, tourist destinations would be a lot cleaner and more attractive.",
          ],
          bankPage: 128,
          videos: [
            { id: 'tfSi3foze3Q', title: 'Using Conditional Sentences in English - 5 Levels of Difficulty' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u7-7a-conditionals',
            title: 'First or second conditional',
            kind: 'mcq',
            instructions: 'Choose the correct verb form.',
            instructionsAr: 'اختر صيغة الفعل الصحيحة.',
            page: 82,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'If you learn the language, you ___ be able to communicate with people.',
                options: [
                  { label: "will", correct: true },
                  { label: "would", correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'If you leave rubbish everywhere, somebody ___ to clear it up.',
                options: [
                  { label: 'will have', correct: true },
                  { label: 'would have', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'If the city charged a tourist tax, they ___ reduce the number of tourists.',
                options: [
                  { label: 'would', correct: true },
                  { label: 'will', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'If we stayed in a small hotel, we ___ help the local economy.',
                options: [
                  { label: 'would', correct: true },
                  { label: 'will', correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'If the hotel gets a good review, it ___ encourage more tourists to visit.',
                options: [
                  { label: 'will', correct: true },
                  { label: 'would', correct: false },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: "If tourists had more respect for local customs, it ___ be better.",
                options: [
                  { label: 'would', correct: true },
                  { label: 'will', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Pronunciation: contractions',
          titleAr: 'النطق: الاختصارات',
          tracks: au(['7.01'], 82),
        },
        {
          type: 'pages',
          images: [img(94, 'Lesson 7A, page 80'), img(95, 'Lesson 7A, page 81'), img(96, 'Lesson 7A, page 82')],
        },
      ],
    },
    {
      id: '7b',
      code: '7B',
      title: 'Globetrotters',
      pages: [83, 85],
      labels: {
        grammar: 'quantifiers',
        vocabulary: 'new experiences; the natural world',
        pronunciation: 'emphasising quantity',
      },
      objectives: ['understand someone talking about moving abroad', 'use quantifiers', 'write a description of an experience'],
      blocks: [
        {
          type: 'exercise',
          exercise: {
            id: 'u7-7b-quantifiers',
            title: 'Quantifiers',
            kind: 'mcq',
            instructions: 'Complete the rules with the correct quantifiers.',
            instructionsAr: 'أكمل القواعد بأدوات الكمية الصحيحة.',
            page: 83,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'We use many, much and ___ to refer to a large number or amount.',
                options: [
                  { label: 'a lot of', correct: true },
                  { label: 'a few', correct: false },
                  { label: 'hardly any', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'We use hardly any and ___ to refer to a small number or amount.',
                options: [
                  { label: 'a bit of', correct: true },
                  { label: 'plenty of', correct: false },
                  { label: 'too much', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'We use a few and ___ only with countable nouns.',
                options: [
                  { label: 'many', correct: true },
                  { label: 'much', correct: false },
                  { label: 'a bit of', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'We use ___ to mean "the right amount".',
                options: [
                  { label: 'enough', correct: true },
                  { label: 'too much', correct: false },
                  { label: 'hardly any', correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'We use too many and ___ to mean "more than we want".',
                options: [
                  { label: 'too much', correct: true },
                  { label: 'enough', correct: false },
                  { label: 'plenty of', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'Online comments about travel',
          titleAr: 'تعليقات على الإنترنت عن السفر',
          paragraphs: [
            'Leah (Uganda): I\u2019d visited hardly any other countries until my twenties. Then I began to go on a lot of trips for work and now I\u2019ve visited five continents.',
            'Milena (USA): I haven\u2019t been to many places outside my own state. I don\u2019t have much time to travel because I work and study.',
            'Sunil (UK): I went to plenty of different countries when I was younger. Now that I have a family I don\u2019t have enough money to travel. Flights and hotels cost too much money.',
            'Miyako (Japan): I went on a few trips when I was a teenager, and fell in love with travelling. Now, whenever I have a bit of money, I spend it on travel.',
            'Kerry (Australia): Lots of people my age travel abroad. We want to see the world while we\u2019re young. That\u2019s why I\u2019m travelling now.',
          ],
        },
        {
          type: 'audio',
          title: 'Pronunciation: emphasising quantity',
          titleAr: 'النطق: التأكيد على الكمية',
          tracks: au(['7.02'], 83),
        },
        {
          type: 'text',
          title: 'Audiobook: moving to Brazil',
          titleAr: 'كتاب صوتي: الانتقال إلى البرازيل',
          paragraphs: [
            'You are going to listen to part of an audiobook by an Englishman who moved to Brazil. In his first weeks, everything was surprising: he saw a mango tree in his garden, shops sold lots of fruits he\u2019d never heard of, and he explored the town and came across a few cafés.',
            'He describes the coffee in the cafés, the noises he hears, the people who accepted him, and what living by the sea means to him. He\u2019d expected to be lonely, but he became friends with some local people.',
          ],
        },
        {
          type: 'audio',
          title: 'Listening: audiobook about Brazil',
          titleAr: 'الاستماع: كتاب صوتي عن البرازيل',
          tracks: au(['7.03'], 84),
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u7-7b-vocab',
            title: 'New experiences: vocabulary',
            kind: 'mcq',
            instructions: 'Match each word/phrase with its meaning.',
            instructionsAr: 'طابق كل كلمة أو عبارة مع معناها.',
            page: 84,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'What does "surprising" mean?',
                options: [
                  { label: 'different to what I thought', correct: true },
                  { label: 'walk around a place to find out about it' },
                  { label: 'find something by chance' },
                  { label: 'see or hear someone or something' },
                  { label: 'let me become part of their group' },
                  { label: 'believe something will happen' },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'What does "explore" mean?',
                options: [
                  { label: 'different to what I thought' },
                  { label: 'walk around a place to find out about it', correct: true },
                  { label: 'find something by chance' },
                  { label: 'see or hear someone or something' },
                  { label: 'let me become part of their group' },
                  { label: 'believe something will happen' },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'What does "come across" mean?',
                options: [
                  { label: 'different to what I thought' },
                  { label: 'walk around a place to find out about it' },
                  { label: 'find something by chance', correct: true },
                  { label: 'see or hear someone or something' },
                  { label: 'let me become part of their group' },
                  { label: 'believe something will happen' },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'What does "notice" mean?',
                options: [
                  { label: 'different to what I thought' },
                  { label: 'walk around a place to find out about it' },
                  { label: 'find something by chance' },
                  { label: 'see or hear someone or something', correct: true },
                  { label: 'let me become part of their group' },
                  { label: 'believe something will happen' },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'What does "accept me" mean?',
                options: [
                  { label: 'different to what I thought' },
                  { label: 'walk around a place to find out about it' },
                  { label: 'find something by chance' },
                  { label: 'see or hear someone or something' },
                  { label: 'let me become part of their group', correct: true },
                  { label: 'believe something will happen' },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'What does "expect" mean?',
                options: [
                  { label: 'different to what I thought' },
                  { label: 'walk around a place to find out about it' },
                  { label: 'find something by chance' },
                  { label: 'see or hear someone or something' },
                  { label: 'let me become part of their group' },
                  { label: 'believe something will happen', correct: true },
                ],
              },
            ],
          },
        },
        {
          type: 'vocab',
          title: 'the natural world',
          titleAr: 'العالم الطبيعي',
          items: [
            { word: 'coast', meaningAr: 'الساحل', example: 'I walked along the coast every morning.', exampleAr: 'كنت أسير بمحاذاة الساحل كل صباح.' },
            { word: 'beach', meaningAr: 'الشاطئ', example: 'Those dogs on the beach were my friends.', exampleAr: 'تلك الكلاب على الشاطئ كانت أصدقائي.' },
            { word: 'landscape', meaningAr: 'المنظر الطبيعي / الطبيعة', example: 'The landscape was never boring.', exampleAr: 'لم يكن المنظر الطبيعي مملاً أبداً.' },
            { word: 'field', meaningAr: 'حقل', example: 'We walked through green fields.', exampleAr: 'سرنا عبر حقول خضراء.' },
            { word: 'valley', meaningAr: 'وادي', example: 'We went over hills, through valleys.', exampleAr: 'تجاوزنا التلال عبر الوديان.' },
            { word: 'stream / river', meaningAr: 'جدول / نهر', example: 'We walked next to streams and rivers.', exampleAr: 'سرنا بجانب الجداول والأنهار.' },
            { word: 'forest', meaningAr: 'غابة', example: 'The path led through a forest.', exampleAr: 'قاد الممر عبر غابة.' },
          ],
          source: 'See also Vocabulary Bank, page 143 (the natural world)',
        },
        {
          type: 'text',
          title: 'Writing: a description of an experience',
          titleAr: 'الكتابة: وصف تجربة',
          paragraphs: [
            'Zeinab writes to describe a cycling trip to Santiago de Compostela in the north of Spain. She mentions meeting people, new ways of doing things, interesting places to visit, the landscape, the food, the weather, local customs, problems, and what she expected before the trip.',
            'Useful phrases to describe feelings and reactions: It was + adjective (It was amazing.) We enjoyed + -ing (We enjoyed exploring.) We were + adjective + to (We were excited to come across beautiful little towns.) I found + noun + adjective (I found the history very interesting.) I\u2019d expected\u2026, but\u2026 (I\u2019d expected the cycling to be really difficult, but it wasn\u2019t too bad.)',
          ],
        },
        {
          type: 'pages',
          images: [img(97, 'Lesson 7B, page 83'), img(98, 'Lesson 7B, page 84'), img(99, 'Lesson 7B, page 85')],
        },
      ],
    },
    {
      id: '7c',
      code: '7C',
      title: 'You must see\u2026!',
      pages: [86, 87],
      labels: {
        grammar: 'How to\u2026 make and respond to recommendations',
        vocabulary: 'describing places',
        pronunciation: 'sounding enthusiastic',
      },
      objectives: ['make and respond to recommendations', 'describe places'],
      blocks: [
        {
          type: 'text',
          title: 'Top things to do in Shanghai',
          titleAr: 'أفضل الأشياء للقيام بها في شنغهاي',
          paragraphs: [
            'Shanghai is China\u2019s largest and richest city. It\u2019s worth a visit to experience this vibrant, exciting and modern city. Here are the top three things you should do in Shanghai.',
            '1. Travel to the top of the famous Shanghai Tower, based in Shanghai\u2019s financial district. From the top of this huge tower you can see fantastic views of the city. This is a great place to enjoy a meal in one of many restaurants.',
            '2. Walk along the Bund and appreciate the many different historical buildings. Enjoy the view of Shanghai\u2019s famous skyline as you look out across the 500 m wide Huangpu River, which splits the city in two. The Bund is also one of the best places to go shopping!',
            '3. Enjoy the green space and peaceful surroundings at Yu Garden, in the old Chinese neighbourhood. Relax as you walk through these beautiful, ancient gardens (built in 1577), cross the narrow, wooden bridges and enjoy looking at the traditional, colourful buildings. Next door is a market where you can drink tea, try some delicious local snacks and buy some souvenirs.',
          ],
        },
        {
          type: 'vocab',
          title: 'describing places',
          titleAr: 'وصف الأماكن',
          items: [
            { word: 'vibrant', meaning: 'full of energy and life', meaningAr: 'نابض بالحياة', example: "It's worth a visit to experience this vibrant, exciting and modern city.", exampleAr: 'يستحق الزيارة لتجربة هذه المدينة النابضة بالحياة والمثيرة والعصرية.' },
            { word: 'modern', meaningAr: 'عصري / حديث', example: 'The buildings are modern.', exampleAr: 'المباني عصرية.' },
            { word: 'ancient', meaningAr: 'قديم / عريق', example: 'This ancient bridge is over 800 years old.', exampleAr: 'هذا الجسر القديم عمره أكثر من 800 عام.' },
            { word: 'narrow / wide', meaningAr: 'ضيّق / واسع', example: "The streets are so narrow you can't drive down them.", exampleAr: 'الشوارع ضيقة جداً بحيث لا يمكنك القيادة فيها.' },
            { word: 'peaceful', meaning: 'quiet and calm', meaningAr: 'هادئ / سِلمي', example: 'I love sitting in the park - it\u2019s so peaceful.', exampleAr: 'أحب الجلوس في الحديقة - إنها هادئة جداً.' },
            { word: 'wooden', meaningAr: 'خشبي', example: 'There are some old wooden benches.', exampleAr: 'هناك بعض المقاعد الخشبية القديمة.' },
            { word: 'colourful', meaningAr: 'ملوّن / زاهي', example: 'The buildings are colourful.', exampleAr: 'المباني ملوّنة.' },
            { word: 'historical', meaningAr: 'تاريخي', example: 'There are many historical buildings in Rome.', exampleAr: 'هناك العديد من المباني التاريخية في روما.' },
            { word: 'traditional', meaningAr: 'تقليدي', example: 'We saw traditional houses in the old town.', exampleAr: 'رأينا بيوتاً تقليدية في البلدة القديمة.' },
            { word: 'famous for', meaningAr: 'مشهور بـ', example: 'The city is famous for its beautiful views.', exampleAr: 'المدينة مشهورة بإطلالاتها الجميلة.' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u7-7c-places',
            title: 'Describing places',
            kind: 'fill-blank',
            instructions: 'Choose the correct word to complete each sentence.',
            instructionsAr: 'اختر الكلمة الصحيحة لإكمال كل جملة.',
            page: 86,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'This',
                answer: 'ancient',
                after: 'bridge is over 800 years old.',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: "The streets are so",
                answer: 'narrow',
                accept: ['wide'],
                after: "you can't drive down them.",
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: "I love sitting in the park - it's so",
                answer: 'peaceful',
                after: '.',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'There are some old',
                answer: 'wooden',
                after: 'benches where you can sit and watch people walk past.',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: 'I prefer cities where the buildings are more',
                answer: 'colourful',
                after: '.',
              },
              {
                id: 'q6',
                kind: 'fill-blank',
                before: 'The city is',
                answer: 'famous',
                after: 'for its beautiful views.',
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Listening: Mark\u2019s call to Sam (Shanghai recommendations)',
          titleAr: 'الاستماع: مكالمة Mark مع Sam (توصيات عن شنغهاي)',
          tracks: au(['7.04', '7.05'], 87),
        },
        {
          type: 'vocab',
          title: 'make and respond to recommendations',
          titleAr: 'تقديم التوصيات والرد عليها',
          items: [
            { word: 'There are a few things you absolutely have to see/do\u2026', meaning: 'strong recommendation', meaningAr: 'هناك بضعة أشياء يجب عليك تماماً رؤيتها أو فعلها…', response: 'a strong way to recommend', responseAr: 'طريقة قوية للتوصية' },
            { word: 'You must visit/try/see\u2026', meaning: 'strong recommendation', meaningAr: 'يجب أن تزور / تجرّب / ترى…', response: 'use must + verb', responseAr: 'استخدم must + الفعل' },
            { word: 'You should definitely visit\u2026', meaning: 'strong recommendation', meaningAr: 'يجب أن تزور بالتأكيد…', response: 'use should + definitely', responseAr: 'استخدم should + definitely' },
            { word: 'Make sure you\u2026', meaning: 'tell someone not to forget', meaningAr: 'تأكد من أنك…', response: 'make sure + present simple', responseAr: 'استخدم make sure + المضارع البسيط' },
            { word: '\u2026 is one of the best things to do\u2026', meaning: 'superlative recommendation', meaningAr: '… من أفضل الأشياء التي يمكن فعلها…', response: "it's one of the best", responseAr: 'استخدم صيغة "it\u2019s one of the best"' },
            { word: 'It\u2019s a lovely/great place to\u2026', meaning: 'recommend a place for an activity', meaningAr: 'إنه مكان رائع / جميل لـ…', response: "it's a lovely place to + verb", responseAr: 'استخدم "it\u2019s a lovely place to" + الفعل' },
            { word: 'Don\u2019t leave without visiting/seeing\u2026', meaning: 'unmissable', meaningAr: 'لا تفوّت زيارة / رؤية…', response: "don't + without + -ing", responseAr: 'استخدم don\u2019t + without + الفعل مع ing' },
            { word: 'Oh wow! How exciting!', meaning: 'respond enthusiastically', meaningAr: 'أوه رائع! يا لها من إثارة!', response: "responding: That's a great idea. / OK, that's a good idea. / That sounds interesting.", responseAr: 'الرد: فكرة رائعة. / حسناً، فكرة جيدة. / يبدو الأمر مثيراً للاهتمام.' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u7-7c-recommend',
            title: 'Making recommendations',
            kind: 'fill-blank',
            instructions: 'Complete the phrases Sam uses to make recommendations.',
            instructionsAr: 'أكمل العبارات التي يستخدمها Sam لتقديم التوصيات.',
            page: 87,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'There are a few things you absolutely',
                answer: 'have to',
                after: 'see/do\u2026',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'You',
                answer: 'must',
                after: 'visit/try/see\u2026',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: 'You should',
                answer: 'definitely',
                after: 'visit\u2026',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'Make',
                answer: 'sure',
                after: 'you\u2026',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: '\u2026 is one of the',
                answer: 'best',
                after: 'things to do\u2026',
              },
              {
                id: 'q6',
                kind: 'fill-blank',
                before: "It's a lovely/",
                answer: 'great',
                after: 'place to\u2026',
              },
              {
                id: 'q7',
                kind: 'fill-blank',
                before: 'You',
                answer: 'can',
                after: 'eat/see/walk\u2026',
              },
              {
                id: 'q8',
                kind: 'fill-blank',
                before: "Don't",
                answer: 'leave',
                after: 'without visiting/seeing\u2026',
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Pronunciation: sounding enthusiastic',
          titleAr: 'النطق: التعبير عن الحماس',
          tracks: au(['7.06', '7.07'], 87),
        },
        {
          type: 'pages',
          images: [img(100, 'Lesson 7C, page 86'), img(101, 'Lesson 7C, page 87')],
        },
      ],
    },
    {
      id: '7d',
      code: '7D',
      title: 'Go solo?',
      pages: [88, 89],
      labels: {
        grammar: 'reflexive pronouns',
        skills: 'a discussion about travel',
      },
      objectives: ['understand people talking about travelling', 'use reflexive pronouns', 'write an essay about why we travel'],
      blocks: [
        {
          type: 'text',
          title: 'BBC Street Interviews: Go solo?',
          titleAr: 'BBC: مقابلات الشارع - هل تسافر وحدك؟',
          paragraphs: [
            'The speakers talk about the most amazing places they have visited: India, Syria, New Zealand, Iceland, Budapest, London and Mount Kilimanjaro. Then they are asked whether they prefer travelling by themselves or with other people.',
          ],
        },
        {
          type: 'video',
          title: 'Watch and note the places',
          titleAr: 'شاهد ودوّن الأماكن',
          videos: [
            {
              title: 'BBC Street Interviews: Go solo?',
              file: 'SO3 B1 U7 BBC StreetInt.mp4',
              page: 88,
            },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u7-7d-video',
            title: 'What the speakers say',
            kind: 'mcq',
            instructions: 'Choose the correct words to complete what the speakers say.',
            instructionsAr: 'اختر الكلمات الصحيحة لإكمال ما يقوله المتحدثون.',
            page: 88,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: "Molly: I prefer my own ___ .",
                options: [
                  { label: 'company', correct: true },
                  { label: 'family', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: "Dan: It can get a bit ___ on your own.",
                options: [
                  { label: 'lonely', correct: true },
                  { label: 'lively', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: "Nikki: Just go on your own, I'd say. ___",
                options: [
                  { label: 'Go on your own, I\u2019d say', correct: true },
                  { label: 'Go with friends, I\u2019d say', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: "Osaid: \u2026 the experience is ___ with my friends or family.",
                options: [
                  { label: 'better', correct: true },
                  { label: 'shared', correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: "Anabel: You can share the memory with them, rather than just by ___ .",
                options: [
                  { label: 'yourself', correct: true },
                  { label: 'alone', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'grammar',
          title: 'reflexive pronouns',
          titleAr: 'ضمائر الانعكاس',
          explanation:
            'We use reflexive pronouns (myself, yourself, himself, herself, itself, ourselves, yourselves, themselves) when the object of a verb is the same person as the subject. The phrase by myself/yourself\u2026 means "alone".',
          explanationAr:
            'نستخدم ضمائر الانعكاس (myself و yourself و himself و herself و itself و ourselves و yourselves و themselves) عندما يكون مفعول الفعل هو نفس الفاعل. وتعني عبارة by myself / yourself... «وحدك».',
          rule: 'myself / yourself / himself / herself / itself / ourselves / yourselves / themselves. By + reflexive pronoun = alone: "Do you prefer travelling by yourself?"',
          ruleAr: 'myself / yourself / himself / herself / itself / ourselves / yourselves / themselves. By + ضمير الانعكاس = وحدك: "Do you prefer travelling by yourself?"',
          table: {
            headers: ['Reflexive pronoun', 'Example'],
            rows: [
              { values: ['myself', 'I like the freedom of travelling by myself.'] },
              { values: ['yourself', 'Do you prefer travelling by yourself?'] },
              { values: ['himself', 'My brother likes travelling by himself.'] },
              { values: ['herself', "Ana prefers walking by herself."] },
              { values: ['ourselves', 'We really enjoyed ourselves.'] },
            ],
          },
          examples: [
            'Do you prefer travelling by yourself?',
            'I like the freedom of travelling by myself.',
            'My brother likes travelling by himself.',
            'Ana prefers walking by herself.',
            'You always go by yourself.',
          ],
          bankPage: 131,
          videos: [
            { id: '6Dna4Tl_YlA', title: '9 Parts of Speech in English - English Grammar Lesson' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u7-7d-reflexive',
            title: 'Reflexive pronouns',
            kind: 'fill-blank',
            instructions: 'Complete the sentences with the correct reflexive pronouns. Add by where necessary.',
            instructionsAr: 'أكمل الجمل بضمائر الانعكاس الصحيحة. أضف by عندما يكون ذلك ضرورياً.',
            page: 90,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'She walked up to the teacher and introduced',
                answer: 'herself',
                after: '.',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: "I always go to the cinema with other people. I don't like going",
                answer: 'by myself',
                accept: ['alone', 'on my own'],
                after: '.',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: 'The cake was lovely, Sarah. Did you make it',
                answer: 'yourself',
                after: '?',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'It was a great party! We really enjoyed',
                answer: 'ourselves',
                after: '.',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: 'I was worried I might fall and hurt',
                answer: 'myself',
                after: '.',
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'Writing: an essay about why we travel',
          titleAr: 'الكتابة: مقال عن لماذا نسافر',
          paragraphs: [
            'Model essay (Why travel?): The main reason to travel is that it can open our minds. We see new sights, meet new people and learn new languages. Things we always thought were "normal" aren\u2019t necessarily normal in other cultures. This applies to customs, architecture, food, even driving. It means that when we get home, we see things with fresh eyes.',
            'Sometimes people get stuck in a routine, doing the same things every day. When we travel, that routine often changes and sometimes we change too. We escape from everyday life and we learn about ourselves.',
            'For many people, travelling provides the most exciting experiences life can offer. If we keep our eyes and ears open, it can change our lives.',
            'Key phrases: I like travelling by myself because\u2026 Travelling with other people can be\u2026 What makes some places special is\u2026 Special places often have\u2026 One thing we can learn from travelling is\u2026 Another thing\u2026',
          ],
        },
        {
          type: 'pages',
          images: [img(102, 'Lesson 7D, page 88'), img(103, 'Lesson 7D, page 89')],
        },
      ],
    },
    {
      id: '7r',
      code: 'Review',
      title: 'Unit 7 Review',
      pages: [90, 90],
      blocks: [
        {
          type: 'text',
          title: 'Review what you have learned',
          titleAr: 'راجع ما تعلمته',
          paragraphs: [
            'Complete the review exercises to practise the grammar and vocabulary of Unit 7: first and second conditionals, quantifiers, and reflexive pronouns.',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u7-7r-conditionals',
            title: 'First conditional sentences',
            kind: 'mcq',
            instructions: 'Match each if-clause with its result and write first conditional sentences.',
            instructionsAr: 'طابق كل جملة شرطية مع نتيجتها، ثم اكتب جملاً شرطية من النوع الأول.',
            page: 90,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'Complete: If you go to bed early every night, ___',
                options: [
                  { label: 'feel better in the morning', correct: true },
                  { label: "won't get fit" },
                  { label: 'have problems at work' },
                  { label: 'open your mind' },
                  { label: "won't pass your exams" },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: "Complete: If you don't exercise, ___",
                options: [
                  { label: 'feel better in the morning' },
                  { label: "won't get fit", correct: true },
                  { label: 'have problems at work' },
                  { label: 'open your mind' },
                  { label: "won't pass your exams" },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'Complete: If you argue with your manager, ___',
                options: [
                  { label: 'feel better in the morning' },
                  { label: "won't get fit" },
                  { label: 'have problems at work', correct: true },
                  { label: 'open your mind' },
                  { label: "won't pass your exams" },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'Complete: If you travel a lot, ___',
                options: [
                  { label: 'feel better in the morning' },
                  { label: "won't get fit" },
                  { label: 'have problems at work' },
                  { label: 'open your mind', correct: true },
                  { label: "won't pass your exams" },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'Complete: If you only study for ten minutes a day, ___',
                options: [
                  { label: 'feel better in the morning' },
                  { label: "won't get fit" },
                  { label: 'have problems at work' },
                  { label: 'open your mind' },
                  { label: "won't pass your exams", correct: true },
                ],
              },
            ],
          },
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u7-7r-text',
            title: 'Choose the correct options',
            kind: 'mcq',
            instructions: 'Complete the text "The best job in the world?" with the correct options.',
            instructionsAr: 'أكمل النص «The best job in the world?» بالخيارات الصحيحة.',
            page: 90,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'A magazine pays you to go to beautiful ___ .',
                options: [
                  { label: 'destinations', correct: true },
                  { label: 'trips', correct: false },
                  { label: 'souvenirs', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'You learn local ___ .',
                options: [
                  { label: 'customs', correct: true },
                  { label: 'festivals', correct: false },
                  { label: 'monuments', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'You visit tourist ___ .',
                options: [
                  { label: 'attractions', correct: true },
                  { label: 'breaks', correct: false },
                  { label: 'tours', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'The main reason to travel is that it can open our minds. Unfortunately, there isn\u2019t ___ chance of that dream coming true.',
                options: [
                  { label: 'much', correct: true },
                  { label: 'a few', correct: false },
                  { label: 'plenty', correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'Make ___ you read the magazines you want to write for.',
                options: [
                  { label: 'sure', correct: true },
                  { label: 'always', correct: false },
                  { label: 'that', correct: false },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'If you ___ your research, you\u2019ll have a better chance of getting published.',
                options: [
                  { label: 'do', correct: true },
                  { label: 'will do', correct: false },
                  { label: 'would', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Review listening',
          titleAr: 'استماع المراجعة',
          tracks: au(['R7.01'], 90),
        },
        {
          type: 'pages',
          images: [img(104, 'Unit 7 Review, page 90')],
        },
      ],
    },
  ],
}