import type { Unit } from '../../types/content'
import { au, img } from '../helpers'

export const unit08: Unit = {
  id: 'unit-8',
  number: 8,
  title: 'know-how',
  phrase: 'talk about skills and abilities, videos, technology and learning',
  overviewPage: 91,
  pages: [91, 103],
  intro:
    'In this unit you talk about your skills and abilities, read about video, describe technical problems and make recommendations, and discuss the best ways to learn a language.',
  objectives: [
    '8A – understand people talking about their skills; talk about your skills and abilities',
    '8B – read about video; make a short video or plan an online video channel',
    '8C – describe a problem and make recommendations',
    '8D – understand a TV programme about a gifted language learner; write a forum comment',
  ],
  video: [
    {
      title: 'BBC Vlogs: Are you good or bad at fixing things?',
      file: 'SO3 B1 U8 BBC Vlogs.mp4',
      page: 91,
    },
    {
      title: 'BBC Programme: A gifted learner',
      file: 'SO3 B1 U8 BBC Programmes.mp4',
      page: 100,
    },
  ],
  lessons: [
    {
      id: '8a',
      code: '8A',
      title: 'Doers and dreamers',
      pages: [92, 94],
      labels: {
        grammar: 'can, could, be able to',
        vocabulary: 'practical abilities; abilities: phrasal verbs',
        pronunciation: 'weak forms of can, could and be able to',
      },
      objectives: ['understand people talking about their skills', 'use can, could and be able to', 'write an anecdote about learning a skill'],
      blocks: [
        {
          type: 'text',
          title: 'Living the dream',
          titleAr: 'يعيش الحلم',
          paragraphs: [
            'Gregoire Kengen is a film-maker and photographer from Belgium. Gregoire travels around in his van (named Henri!), films his experiences and uploads the videos to YouTube. His YouTube channel, gregsway, has over 200,000 subscribers.',
            'One reason why Gregoire is popular is that he\u2019s very practical and creative. For example, he turned his van into a mobile studio, added new parts and installed electricity. His van was made in 1990, and he sometimes has to repair things that go wrong or replace old parts. He always finds a way!',
            'In 2017, Gregoire started a new project. He and a friend built a tiny house mainly from wood. With the help of an architect, he designed it and calculated what size it should be and what materials he needed. As the house is far from civilisation, they had to solve a few problems such as how to get water and electricity to it. They arranged access to running water, put up shelves and added a power supply. Now they rent the house to guests.',
            'Gregoire started fixing things as a hobby, but he was able to turn his hobby into a job and a way of life. For this reason, some say he\u2019s really living the dream!',
          ],
        },
        {
          type: 'vocab',
          title: 'practical abilities; abilities: phrasal verbs',
          titleAr: 'مهارات عملية؛ القدرات: أفعال مركبة',
          items: [
            { word: 'repair', meaning: 'fix something broken', meaningAr: 'يُصلح', example: 'He sometimes has to repair things that go wrong.', exampleAr: 'يضطر أحياناً لإصلاح الأشياء التي تتعطل.' },
            { word: 'replace', meaning: 'buy something new because the old one doesn\u2019t work', meaningAr: 'يستبدل', example: 'He replaced the old parts of his van.', exampleAr: 'استبدل الأجزاء القديمة من شاحنته.' },
            { word: 'upload', meaning: 'put something on the internet', meaningAr: 'يرفع على الإنترنت', example: 'He uploads the videos to YouTube.', exampleAr: 'يرفع الفيديوهات إلى يوتيوب.' },
            { word: 'put up', meaning: 'fix something to a wall', meaningAr: 'يعلّق على الحائط / يثبّت', example: 'They put up shelves.', exampleAr: 'علّقوا أرففاً.' },
            { word: 'calculate', meaning: 'work out a number', meaningAr: 'يحسب', example: 'He calculated what size it should be.', exampleAr: 'حسب الحجم الذي ينبغي أن يكون عليه.' },
            { word: 'design', meaning: 'draw and plan something new', meaningAr: 'يصمّم', example: 'He designed the tiny house.', exampleAr: 'صمّم المنزل الصغير.' },
            { word: 'install', meaning: 'put in and connect (technology)', meaningAr: 'يركّب', example: 'He installed electricity.', exampleAr: 'ركّب الكهرباء.' },
            { word: 'turn (something) into (something else)', meaning: 'change something into something different', meaningAr: 'يحوّل (شيئاً) إلى (شيء آخر)', example: 'He turned his van into a mobile studio.', exampleAr: 'حوّل شاحنته إلى استوديو متنقل.' },
            { word: 'solve a problem', meaning: 'find an answer to a problem', meaningAr: 'يحلّ مشكلة', example: 'They had to solve a few problems.', exampleAr: 'كان عليهم حلّ بضع مشكلات.' },
            { word: 'arrange', meaning: 'organise', meaningAr: 'يرتّب / ينظّم', example: 'They arranged access to running water.', exampleAr: 'رتّبوا الحصول على مياه جارية.' },
          ],
          source: 'See also Vocabulary Bank, page 144 (abilities: phrasal verbs)',
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8a-vocab',
            title: 'Phrasal verbs for abilities',
            kind: 'fill-blank',
            instructions: 'Complete the sentences with the correct verb.',
            instructionsAr: 'أكمل الجمل بالفعل الصحيح.',
            page: 92,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'I need to',
                answer: 'repair',
                after: 'my bike - the brakes don\u2019t work.',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'When my old phone broke, I decided to',
                answer: 'replace',
                after: 'it with a new one.',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: 'I always',
                answer: 'upload',
                after: 'my holiday photos to social media.',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'Could you help me',
                answer: 'put up',
                after: 'this shelf in the kitchen?',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: 'Can you',
                answer: 'calculate',
                after: 'the price of all these materials?',
              },
              {
                id: 'q6',
                kind: 'fill-blank',
                before: 'We need to',
                answer: 'install',
                after: 'the new software on all the computers.',
              },
              {
                id: 'q7',
                kind: 'fill-blank',
                before: 'She managed to',
                answer: 'solve',
                after: 'the problem with the printer.',
              },
              {
                id: 'q8',
                kind: 'fill-blank',
                before: 'Let\u2019s',
                answer: 'arrange',
                after: 'a meeting for next week.',
              },
            ],
          },
        },
        {
          type: 'grammar',
          title: 'can, could, be able to',
          titleAr: 'القدرة: can، could، be able to',
          explanation:
            'We use can / can\u2019t for ability in the present, and could / couldn\u2019t for general ability in the past. Be able to is used for all tenses and for specific past achievements.',
          explanationAr:
            'نستخدم can و can\u2019t للتعبير عن القدرة في الحاضر، و could و couldn\u2019t للتعبير عن قدرة عامة في الماضي. ونستخدم be able to مع جميع الأزمنة، وكذلك عند الحديث عن إنجاز محدد ناجح في الماضي.',
          rule: "Present: can / can't / am able to. Past: could / couldn't for general ability; was/were able to for specific successful actions. Be able to works with other tenses: 'I'm able to install a washing machine.'",
          ruleAr:
            'في الحاضر: can / can\u2019t / am able to. في الماضي: could / couldn\u2019t للقدرة العامة، و was/were able to للأعمال الناجحة المحددة. ويعمل be able to مع الأزمنة الأخرى، مثل: "I\u2019m able to install a washing machine."',
          table: {
            headers: ['Form', 'Use', 'Example'],
            rows: [
              { values: ["can / can't", 'present ability', "I can fix a roof. I can't play video games."] },
              { values: ["could / couldn't", 'past general ability', 'I could draw quite well. I couldn\u2019t do any of that a few years ago.'] },
              { values: ['was/were able to', 'past specific achievement', 'I was able to use my skills to design clothes.'] },
              { values: ["be able to (+ other tenses)", 'future / perfect ability', "I'm able to install a washing machine."] },
            ],
          },
          examples: [
            'I could draw quite well.',
            'I was able to use my skills to design clothes.',
            'I can fix a roof.',
            "I'm able to install a washing machine.",
            "I can't play video games.",
            "I couldn't do any of that a few years ago.",
          ],
          bankPage: 132,
          videos: [
            { id: 'FMGxeChtYLc', title: 'English Modal Verbs - May, Might, Could, Can - Talking About Possibilities' },
            { id: '4GMU08J98MQ', title: 'Complete Guide to English Modal Verbs - English Grammar Lesson' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8a-ability',
            title: 'Present or past ability',
            kind: 'mcq',
            instructions: 'Choose the correct form.',
            instructionsAr: 'اختر الصيغة الصحيحة.',
            page: 93,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'Now he has his own fashion business. When he was young, he ___ draw quite well.',
                options: [
                  { label: 'could', correct: true },
                  { label: 'can', correct: false },
                  { label: 'is able to', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'She has a company that fixes problems in buildings. She ___ fix a roof.',
                options: [
                  { label: 'can', correct: true },
                  { label: 'could', correct: false },
                  { label: 'was able to', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: "\u201cI ___ play video games,\u201d he says. (present, not possible)",
                options: [
                  { label: "can't", correct: true },
                  { label: "couldn't", correct: false },
                  { label: "wasn't able to", correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: "She first built a computer when she was ten. She ___ use her skills to design clothes.",
                options: [
                  { label: 'was able to', correct: true },
                  { label: 'can', correct: false },
                  { label: "is able to", correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Listening: how people use practical skills',
          titleAr: 'استماع: كيف يستخدم الناس مهارات عملية',
          tracks: au(['8.01'], 93),
        },
        {
          type: 'audio',
          title: 'Pronunciation: weak forms of can, could and be able to',
          titleAr: 'النطق: الأشكال الضعيفة لكلمات can و could و be able to',
          tracks: au(['8.02'], 93),
        },
        {
          type: 'text',
          title: 'Writing: an anecdote about learning a skill',
          titleAr: 'كتابة: قصة قصيرة عن تعلّم مهارة',
          paragraphs: [
            'Model text (Marta Freire Alves): "I could swim almost before I could walk. My parents were keen surfers and we lived next to the beach. I was able to surf when I was five and I got my first surfboard at the age of six."',
            'When she was twelve, she learnt how to repair surfboards because she and her friends couldn\u2019t replace their old boards with new ones. Her mother showed her what to do. After a few months, she could do it alone. These days she can still repair old surfboards, and young surfers bring their broken boards to her because she\u2019s the only one who\u2019s able to fix them!',
            'Useful phrases to describe the sequence and time: at the age of\u2026, when I was twelve, at first, after a few months, these days.',
          ],
        },
        {
          type: 'pages',
          images: [img(106, 'Lesson 8A, page 92'), img(107, 'Lesson 8A, page 93'), img(108, 'Lesson 8A, page 94')],
        },
      ],
    },
    {
      id: '8b',
      code: '8B',
      title: 'Video everywhere',
      pages: [95, 97],
      labels: {
        grammar: 'active and passive',
        vocabulary: 'video collocations; technology 1',
        pronunciation: 'emphasising important information',
      },
      objectives: ['read about video', 'use active and passive forms', 'make a short video or plan an online video channel'],
      blocks: [
        {
          type: 'vocab',
          title: 'video collocations',
          titleAr: 'الكلمات المصاحبة للفيديو',
          items: [
            { word: 'clip', meaning: 'a short piece from a longer video', meaningAr: 'مقطع', example: 'A video clip is a short piece from a longer video.', exampleAr: 'مقطع الفيديو هو جزء قصير من فيديو أطول.' },
            { word: 'share', meaning: 'send a video to other people on social media', meaningAr: 'يشارك', example: 'If you share a video, other people can watch it too.', exampleAr: 'إذا شاركت فيديو، يمكن للآخرين مشاهدته أيضاً.' },
            { word: 'edit', meaning: 'make a video shorter and keep the best parts', meaningAr: 'يحرّر / يعدّل', example: 'When you edit a video, you make it shorter.', exampleAr: 'عندما تحرّر فيديو، تجعله أقصر.' },
            { word: 'like', meaning: 'show you enjoy a video', meaningAr: 'يُعجب بـ', example: 'You might like the video.', exampleAr: 'قد يعجبك الفيديو.' },
            { word: 'comment', meaning: 'write a response on a video', meaningAr: 'يعلّق', example: 'You might comment on it.', exampleAr: 'قد تعلّق عليه.' },
            { word: 'make', meaning: 'create a video', meaningAr: 'يصنع / ينشئ', example: 'A lot of people make videos to use for marketing.', exampleAr: 'كثير من الناس يصنعون فيديوهات لاستخدامها في التسويق.' },
            { word: 'vlog', meaning: 'a video blog', meaningAr: 'مدونة فيديو', example: 'A video podcast is often called a vlog.', exampleAr: 'غالباً ما يُسمّى البودكاست المرئي فلوق.' },
            { word: 'upload', meaning: 'put a video online', meaningAr: 'يرفع', example: 'Hundreds of hours of video are uploaded to YouTube every minute.', exampleAr: 'يُرفع مئات الساعات من الفيديو إلى يوتيوب كل دقيقة.' },
          ],
          source: 'See also Vocabulary Bank, page 144 (technology 1)',
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8b-collocations',
            title: 'Video collocations',
            kind: 'fill-blank',
            instructions: 'Complete the sentences with the correct word.',
            instructionsAr: 'أكمل الجمل بالكلمة الصحيحة.',
            page: 95,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'The first thing I do in the morning is',
                answer: 'turn',
                accept: ['switch', 'put'],
                after: 'my computer on.',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: "I watch 'how to' videos when I need to",
                answer: 'install',
                after: 'an update.',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: "I can't watch films on my phone because it",
                answer: 'runs',
                accept: ['goes'],
                after: 'out of charge too quickly.',
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'Watch, like, share',
          titleAr: 'شاهد، أُعجب بـ، شارك',
          paragraphs: [
            'Video is everywhere. We watch, like, share and make videos more than ever before. Every minute, hundreds of hours of video are uploaded to YouTube. Video has changed how we entertain ourselves, how we communicate, how we share information and how we learn.',
            'Learning: we absorb information more quickly from videos than from reading texts. Videos are naturally appealing, because our brains are programmed to notice movement, so we pay attention more easily. We remember information we watch in videos for longer. Video is being used more and more in education. People watch instructional how-to videos to do all kinds of things: improve their cooking skills, learn new languages, learn musical instruments or do their make-up. Vlogs are popular, too, where people film themselves doing everyday tasks like cleaning, cooking and shopping. Study-with-me videos show people silently studying. When students watch these videos, they feel more motivated to stay focused.',
            'Communication: teenagers in particular often like using video as a way to communicate. Many love sharing and commenting on videos of themselves spending time with friends or sharing an exciting holiday experience. In 2019, 10 billion videos were watched every day on Snapchat.',
            'Entertainment: all the traditional forms of entertainment are available online. One newer trend is Mukbang videos, which originated in South Korea - "eating broadcast". The host is filmed eating a large meal while chatting to the viewer.',
          ],
        },
        {
          type: 'audio',
          title: 'Listening: people talking about videos',
          titleAr: 'استماع: أشخاص يتحدثون عن الفيديوهات',
          tracks: au(['8.03'], 95),
        },
        {
          type: 'grammar',
          title: 'active and passive',
          titleAr: 'المبني للمعلوم والمبني للمجهول',
          explanation:
            'In the active voice, the subject does the action: "People share the videos." In the passive voice, the important information is the action or the thing affected, not who did it.',
          explanationAr:
            'في الجملة المعلومة، الفاعل هو الذي يقوم بالفعل، مثل: "People share the videos." أما في الجملة المجهولة، فالمهم هو الفعل أو الشيء الذي تأثر به، وليس من قام بالفعل.',
          rule: 'Passive: be + past participle. Present: is/are + past participle ("Hundreds of hours of video are uploaded."). Past: was/were + past participle ("Journalists were sent somewhere to report."). We use the passive when it \u2019s not important or not known who does or did the action.',
          ruleAr:
            'الجملة المجهولة: be + اسم المفعول (past participle). في الحاضر: is/are + اسم المفعول، مثل: "Hundreds of hours of video are uploaded." وفي الماضي: was/were + اسم المفعول، مثل: "Journalists were sent somewhere to report." ونستخدم الجملة المجهولة عندما لا يكون مهماً أو معروفاً من قام بالفعل.',
          table: {
            headers: ['Active', 'Passive'],
            rows: [
              { values: ['People watch these videos.', 'These kinds of videos are watched every day.'] },
              { values: ['People shared the video more than 6 million times.', 'The video was shared more than 6 million times.'] },
              { values: ['The teachers give the students homework.', 'The students are given homework every day.'] },
              { values: ['Jenna uploaded the clip to YouTube.', 'The clip was uploaded to YouTube.'] },
            ],
          },
          examples: [
            'Every minute, hundreds of hours of video are uploaded to YouTube.',
            'Every year, more and more videos are shared online.',
            'In the past, journalists were sent somewhere to report on a news event.',
            'When students watch these videos, they feel more motivated.',
          ],
          bankPage: 133,
          videos: [
            { id: 'CmqOXaSUpFo', title: 'How to Use the Passive Voice in English - English Grammar Lesson' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8b-passive',
            title: 'Active and passive',
            kind: 'fill-blank',
            instructions: 'Complete the sentences with the correct active or passive form of the verb in brackets.',
            instructionsAr: 'أكمل الجمل بالصيغة الصحيحة (المعلوم أو المجهول) للفعل الموجود بين القوسين.',
            page: 102,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'The hashtag symbol (#) has another name: it',
                answer: 'is called',
                after: 'an octothorpe. (call)',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'The English language',
                answer: 'is spoken',
                after: 'as a second language by nearly 2 billion people. (speak)',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: 'Only 350 million people',
                answer: 'speak',
                after: 'English as a first language. (speak)',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'The first soft drink that',
                answer: 'was taken',
                after: 'into space was a cola drink. (take)',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: 'The speed of a computer mouse',
                answer: 'is measured',
                accept: ['was measured'],
                after: "in 'Mickeys'. (measure)",
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Pronunciation: emphasising important information',
          titleAr: 'النطق: إبراز المعلومة المهمة',
          tracks: au(['8.04', '8.05'], 97),
        },
        {
          type: 'pages',
          images: [img(109, 'Lesson 8B, page 95'), img(110, 'Lesson 8B, page 96'), img(111, 'Lesson 8B, page 97')],
        },
      ],
    },
    {
      id: '8c',
      code: '8C',
      title: 'Help!',
      pages: [98, 99],
      labels: {
        grammar: 'How to... describe a problem and make recommendations',
        vocabulary: 'technical problems; technology 2',
        pronunciation: 'contrastive stress',
      },
      objectives: ['describe a problem with technology', 'make recommendations', 'use contrastive stress'],
      blocks: [
        {
          type: 'text',
          title: 'Do you suffer from Computer Stress Syndrome?',
          titleAr: 'هل تعاني من متلازمة إجهاد الكمبيوتر؟',
          paragraphs: [
            'It could be the one thing that stresses us out more than anything else in our work life - technical problems. Your phone isn\u2019t working and you can\u2019t download any apps. You finish writing an essay or a report and then realise you\u2019ve just deleted the files by mistake, and lost everything. Or maybe the photocopier is out of order just when you need to copy an important document. Your computer keeps crashing in the middle of a meeting or you can\u2019t open a file or attachment on your laptop. Perhaps you\u2019ve forgotten your password, or you have a slow internet connection. On top of all this, you find the printer is broken. You call the technical department but after waiting for twenty minutes to speak to a real person, you get cut off.',
            'All these technical problems contribute to Computer Stress Syndrome, something many of us suffer from. When the technology works, it\u2019s great. When it fails, it\u2019s a nightmare.',
          ],
        },
        {
          type: 'vocab',
          title: 'technical problems',
          titleAr: 'مشاكل تقنية',
          items: [
            { word: 'crash', meaning: 'stop working suddenly (of a computer)', meaningAr: 'يتوقف فجأة / ينهار', example: 'My computer keeps crashing in the middle of a meeting.', exampleAr: 'حاسوبي يستمر في الانهيار في منتصف الاجتماع.' },
            { word: 'out of order', meaning: 'not working (of a machine)', meaningAr: 'معطّل', example: 'The photocopier is out of order.', exampleAr: 'آلة التصوير معطّلة.' },
            { word: 'broken', meaning: 'damaged, not working', meaningAr: 'مكسور / معطّل', example: 'The printer is broken.', exampleAr: 'الطابعة معطّلة.' },
            { word: 'run out of charge', meaning: 'have no power left a device', meaningAr: 'تنفد البطارية / الشحن', example: 'My phone runs out of charge too quickly.', exampleAr: 'هاتفي تنفد شحنته بسرعة كبيرة.' },
            { word: 'lose the wifi signal', meaning: 'stop getting internet', meaningAr: 'يفقد إشارة الواي فاي', example: 'I lost the wifi signal.', exampleAr: 'فقدت إشارة الواي فاي.' },
            { word: 'open / download / attach a file', meaning: 'open, save or send a file', meaningAr: 'يفتح / ينزّل / يرفق ملفاً', example: 'I can\u2019t open a file or attachment on my laptop.', exampleAr: 'لا أستطيع فتح ملف أو مرفق على حاسوبي المحمول.' },
            { word: 'create / change / forget a password', meaning: 'make, change or forget a password', meaningAr: 'ينشئ / يغيّر / ينسى كلمة مرور', example: 'You can\u2019t use your account until you log in and create a new password.', exampleAr: 'لا يمكنك استخدام حسابك حتى تسجّل الدخول وتنشئ كلمة مرور جديدة.' },
            { word: 'slow internet connection', meaning: 'internet that works slowly', meaningAr: 'اتصال إنترنت بطيء', example: 'You have a slow internet connection.', exampleAr: 'لديك اتصال إنترنت بطيء.' },
            { word: 'get cut off', meaning: 'lose the connection to a call', meaningAr: 'ينقطع الاتصال', example: 'I get cut off after waiting for twenty minutes.', exampleAr: 'يُنقطع اتصالي بعد انتظار عشرين دقيقة.' },
          ],
          source: 'See also Vocabulary Bank, page 145 (technology 2)',
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8c-tech',
            title: 'Technical problems',
            kind: 'fill-blank',
            instructions: 'Complete the sentences about some more technical problems with the correct form of the words in bold.',
            instructionsAr: 'أكمل الجمل عن بعض المشاكل التقنية الإضافية بالصيغة الصحيحة للكلمات المكتوبة بالخط العريض.',
            page: 98,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: '1 The heating is',
                answer: 'broken',
                after: '. We need to fix it because the house is really cold!',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: '2 My phone',
                answer: 'keeps crashing',
                after: " but it keeps restarting.! I can't download any apps.",
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: '3 I sent the email, but I forgot to send the file as an',
                answer: 'attachment',
                after: '.',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: '4 My laptop sometimes',
                answer: 'crashes',
                after: ' when I download large files. It just switches off.',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: '5 I was using the internet, but then I suddenly lost the wifi',
                answer: 'signal',
                after: '.',
              },
              {
                id: 'q6',
                kind: 'fill-blank',
                before: '6 You can\u2019t use your account until you log in and create a new',
                answer: 'password',
                after: '.',
              },
              {
                id: 'q7',
                kind: 'fill-blank',
                before: '7 We only managed to talk for a few minutes before we',
                answer: 'got cut off',
                after: '.',
              },
              {
                id: 'q8',
                kind: 'fill-blank',
                before: '8 The lift was out of',
                answer: 'order',
                after: ', so I had to use the stairs.',
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Listening: someone describes a problem',
          titleAr: 'استماع: شخص يصف مشكلة',
          tracks: au(['8.06'], 99),
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8c-howto',
            title: 'How to... describe a problem and make recommendations',
            kind: 'mcq',
            instructions: 'Choose the correct word to complete the phrases.',
            instructionsAr: 'اختر الكلمة الصحيحة لإكمال العبارات.',
            page: 99,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'There\u2019s a 1 ___ with...',
                options: [
                  { label: 'problem', correct: true },
                  { label: 'mistake', correct: false },
                  { label: 'issue', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'The ... isn\u2019t 2 ___.',
                options: [
                  { label: 'working', correct: true },
                  { label: 'repairing', correct: false },
                  { label: 'fixing', correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'It 3 ___ (crashing).',
                options: [
                  { label: 'keeps', correct: true },
                  { label: 'stops', correct: false },
                  { label: 'ends', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'I think it\u2019s 4 ___.',
                options: [
                  { label: 'broken', correct: true },
                  { label: 'tried', correct: false },
                  { label: 'time', correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'Have you 5 ___ + -ing ...?',
                options: [
                  { label: 'tried', correct: true },
                  { label: 'worked', correct: false },
                  { label: 'needs', correct: false },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'Maybe you 6 ___ ...',
                options: [
                  { label: 'could', correct: true },
                  { label: 'working', correct: false },
                  { label: 'every', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Listening: check the phrases',
          titleAr: 'استماع: تحقّق من العبارات',
          tracks: au(['8.07'], 99),
        },
        {
          type: 'audio',
          title: 'Pronunciation: contrastive stress',
          titleAr: 'النطق: التشديد التقابلي',
          tracks: au(['8.08'], 99),
        },
        {
          type: 'grammar',
          title: 'How to... describe a problem and make recommendations',
          titleAr: 'كيف... تصف مشكلة وتقدّم توصيات',
          explanation:
            'To describe a problem: There\u2019s a problem with... / The ... isn\u2019t working. / I can\u2019t ... / It won\u2019t ... / It keeps (crashing). / When/Every time I ... , it ... / I think it\u2019s (broken).',
          explanationAr:
            'لوصف مشكلة نستخدم عبارات مثل: There\u2019s a problem with... / The ... isn\u2019t working. / I can\u2019t ... / It won\u2019t ... / It keeps (crashing). / When/Every time I ... , it ... / I think it\u2019s (broken).',
          rule: 'To make recommendations: Have you tried + -ing ...? / Try + -ing ... / Have you checked ...? / Maybe you could ... + verb. To respond: Yes, I\u2019ll try that. / Yes, that works. / Yes, it\u2019s working now.',
          ruleAr:
            'لتقديم توصيات: Have you tried + -ing ...؟ / Try + -ing ... / Have you checked ...؟ / Maybe you could ... + فعل. للرد: Yes, I\u2019ll try that. / Yes, that works. / Yes, it\u2019s working now.',
          table: {
            headers: ['Describing a problem', 'Making a recommendation', 'Solving the problem'],
            rows: [
              { values: ["There's a problem with...", 'Have you tried + -ing ...?', "Yes, I'll try that."] },
              { values: ["The ... isn't working.", 'Try + -ing ...', 'Yes, that works.'] },
              { values: ["I can't ... / It won't ...", 'Have you checked ...?', "Yes, it's working now."] },
              { values: ['It keeps (crashing).', 'Maybe you could ...', ''] },
              { values: ["When/Every time I..., it...", '', ''] },
              { values: ["I think it's (broken).", '', ''] },
            ],
          },
          examples: [
            "There's a problem with my internet connection.",
            'The printer isn\u2019t working.',
            "It keeps crashing when I open the file.",
            'Have you tried restarting it?',
            'Maybe you could check the wifi.',
          ],
          videos: [
            { id: '4GMU08J98MQ', title: 'Complete Guide to English Modal Verbs - English Grammar Lesson' },
            { id: 'fMBHNI2Tyq8', title: 'How to Use Should, Ought to, Supposed to and Had Better - English Modal Verbs Lesson' },
            { id: '0djfJqWhnpY', title: 'How to Use the Present Continuous - English Verb Tenses Grammar Lesson' },
          ],
        },
        {
          type: 'pages',
          images: [img(112, 'Lesson 8C, page 98'), img(113, 'Lesson 8C, page 99')],
        },
      ],
    },
    {
      id: '8d',
      code: '8D',
      title: 'A gifted learner',
      pages: [100, 101],
      labels: {
        grammar: '-ing form',
        skills: 'the best ways to learn a language',
        writing: 'a forum comment about language learning',
      },
      objectives: ['understand a BBC programme about a gifted language learner', 'use the -ing form', 'write a forum comment about language learning'],
      blocks: [
        {
          type: 'text',
          title: 'Wendy: a gifted learner',
          titleAr: 'ويندي: متعلّمة موهوبة',
          paragraphs: [
            'Wendy started learning languages at age two and she can now speak lots of them. She spends 60 minutes each week talking to her teachers, and she has picked up thousands of new words.',
            'Languages are easy for Wendy because she started early and she never stops. Watching a video clip about Wendy and other gifted language learners shows how the brain \u2019s ability to learn languages develops.',
          ],
        },
        {
          type: 'grammar',
          title: '-ing form',
          titleAr: 'صيغة -ing',
          explanation:
            "Some verbs are followed by the -ing form of another verb: I started learning them. She spends an hour every week talking to different people.",
          explanationAr:
            'بعض الأفعال يتبعها صيغة -ing من فعل آخر، مثل: I started learning them. She spends an hour every week talking to different people.',
          rule: 'Verbs followed by -ing: enjoy, hate, imagine, like, love, practise, recommend, remember, spend time, start, stop, suggest, try, etc. Example: I like learning languages.',
          ruleAr:
            'الأفعال التي يتبعها صيغة -ing: enjoy, hate, imagine, like, love, practise, recommend, remember, spend time, start, stop, suggest, try، وغيرها. مثال: I like learning languages.',
          table: {
            headers: ['Verb + -ing', 'Example'],
            rows: [
              { values: ['start / begin', 'I started learning them.'] },
              { values: ['spend time', 'She spends an hour every week talking to different people.'] },
              { values: ['enjoy / like / love / hate', 'Personally, I enjoy studying with other people more than by myself.'] },
              { values: ['practise', 'I practise listening to songs.'] },
              { values: ['recommend / suggest', 'I recommend going to a class.'] },
              { values: ['imagine / remember', 'I remember listening to my favourite British bands years ago.'] },
            ],
          },
          examples: [
            'I started learning them.',
            'She spends an hour every week talking to different people.',
            'I like learning languages.',
            "I can't stand translating!",
            'I recommend going to a class.',
          ],
          bankPage: 135,
          videos: [
            { id: '0djfJqWhnpY', title: 'How to Use the Present Continuous - English Verb Tenses Grammar Lesson' },
            { id: '6Dna4Tl_YlA', title: '9 Parts of Speech in English - English Grammar Lesson' },
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8d-ing',
            title: '-ing form',
            kind: 'fill-blank',
            instructions: 'Find five mistakes and correct them. (Write the corrected phrase.)',
            instructionsAr: 'ابحث عن خمسة أخطاء وصحّحها. (اكتب العبارة المصححة).',
            page: 102,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'Find 5 mistakes:',
                answer: 'learning',
                after: " (I remember try to learn Latin at school.)",
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'Find 5 mistakes:',
                answer: 'reading',
                after: " (We practised to read reading texts aloud.)",
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: 'Find 5 mistakes:',
                answer: 'translating',
                after: " (I can't stand to translate translating!)",
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'Find 5 mistakes:',
                answer: 'telling',
                after: " (The teacher kept to tell to tell us it was really important.)",
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: 'Find 5 mistakes:',
                answer: 'explaining',
                after: " (He liked to explain enjoyed explaining that Latin was the root of many languages.)",
              },
            ],
          },
        },
        {
          type: 'audio',
          title: 'Listening: learning Arabic',
          titleAr: 'استماع: تعلّم اللغة العربية',
          tracks: au(['8.09'], 101),
        },
        {
          type: 'text',
          title: 'Language learning forum',
          titleAr: 'منتدى تعلّم اللغات',
          paragraphs: [
            'Sandra wrote: "I\u2019m moving to France for work next year. Does anyone have any tips for learning a new language quickly?\"',
            'Divya replied: "Personally, I enjoy studying with other people more than by myself, so I recommend going to a class and using a grammar book. You need to know the basics, which you can get from a book, but you also have to practise speaking the language.\"',
            'Jun Lee replied: "Try listening to songs in French. That\u2019s a really fun way to learn. I remember listening to my favourite British bands years ago, which is how I learnt English!\"',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8d-forum',
            title: 'Write a response to Sandra\u2019s comment',
            kind: 'mcq',
            instructions: 'Choose the best way to write a forum comment about language learning.',
            instructionsAr: 'اختر أفضل طريقة لكتابة تعليق في المنتدى عن تعلّم اللغات.',
            page: 101,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'Good tips to start a forum comment:',
                options: [
                  { label: 'You should try watching films or TV programmes.', correct: true },
                  { label: 'You should tried watching films or TV programmes.', correct: false },
                  { label: 'Good luck with moving to France and train.', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'pages',
          images: [img(114, 'Lesson 8D, page 100'), img(115, 'Lesson 8D, page 101')],
        },
      ],
    },
    {
      id: 'review',
      code: 'Review',
      title: 'Review',
      pages: [102, 102],
      labels: {
        grammar: 'can, could, be able to; active and passive; -ing form',
        vocabulary: 'skills, video, technology and learning',
      },
      objectives: ['review the grammar and vocabulary of Unit 8'],
      blocks: [
        {
          type: 'exercise',
          exercise: {
            id: 'u8-review-ability',
            title: 'Revision: can, could, be able to',
            kind: 'mcq',
            instructions: 'Choose the correct words to complete the sentences.',
            instructionsAr: 'اختر الكلمات الصحيحة لإكمال الجمل.',
            page: 102,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'I can\u2019t / am able / can type fast.',
                options: [
                  { label: 'can\u2019t', correct: true },
                  { label: 'am able', correct: false },
                  { label: 'can', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'When I first heard English, I couldn\u2019t understand anything.',
                options: [
                  { label: "couldn't understand anything", correct: true },
                  { label: "wasn't able understand anything", correct: false },
                  { label: "couldn't understood anything", correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'Last weekend I didn\u2019t have to work so I was able to relax a little.',
                options: [
                  { label: 'was able to relax', correct: true },
                  { label: 'could to relax', correct: false },
                  { label: 'can relax', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-review-passive',
            title: 'Revision: active and passive',
            kind: 'fill-blank',
            instructions: 'Complete the sentences with the correct active or passive form of the verb in brackets.',
            instructionsAr: 'أكمل الجمل بالصيغة الصحيحة (المعلوم أو المجهول) للفعل الموجود بين القوسين.',
            page: 102,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'Mosquitoes',
                answer: 'are attracted',
                after: ' to people who have just eaten bananas. (attract)',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'The first T-model cars that',
                answer: 'were produced',
                after: ' by Ford were painted different colours (grey, green, blue and red), not just black. (produce)',
              },
            ],
          },
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-review-vocab',
            title: 'Revision: vocabulary',
            kind: 'fill-blank',
            instructions: 'Complete the sentences with the words and phrases in the box.',
            instructionsAr: 'أكمل الجمل بالكلمات والعبارات الموجودة في الصندوق.',
            page: 102,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: '1 Have you ever',
                answer: 'repaired',
                after: ' something you own?',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: '2 Do you know how to',
                answer: 'upload',
                after: ' a video to YouTube?',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: '3 When was the last time you',
                answer: 'installed',
                after: ' a new program on your computer?',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: '4 Have you ever',
                answer: 'put up',
                after: ' pictures on the walls of your house?',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: '5 Can you',
                answer: 'calculate',
                after: ' how much you spend on coffee each month?',
              },
              {
                id: 'q6',
                kind: 'fill-blank',
                before: '6 Have you',
                answer: 'arranged',
                after: ' anything with your friends for this evening?',
              },
              {
                id: 'q7',
                kind: 'fill-blank',
                before: '7 How often do you',
                answer: 'replace',
                after: ' your phone with a newer model?',
              },
              {
                id: 'q8',
                kind: 'fill-blank',
                before: '8 When was the last time you had to',
                answer: 'solve',
                after: ' a problem?',
              },
            ],
          },
        },
        {
          type: 'pages',
          images: [img(116, 'Unit 8 Review, page 102')],
        },
      ],
    },
    {
      id: '8r',
      code: '8R',
      title: 'Extra review',
      pages: [103, 103],
      labels: {
        grammar: 'can, could, be able to; -ing and infinitive forms',
        vocabulary: 'technology; phrasal verbs',
      },
      objectives: ['revise Unit 8 language with extra practice'],
      blocks: [
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8r-6a',
            title: '6A Match the sentence halves',
            kind: 'mcq',
            instructions: 'Match the two parts of each sentence.',
            instructionsAr: 'طابق جزأي كل جملة.',
            page: 103,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'Complete: I never comment ___',
                options: [
                  { label: 'on videos online.', correct: true },
                  { label: 'clips of shows these days, not full programmes.' },
                  { label: "podcasts when I'm on the bus or train." },
                  { label: "a video because I don't like to see myself onscreen." },
                  { label: 'photos of my dinner with friends.' },
                  { label: 'online posts carefully before I share them.' },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'Complete: I usually watch short ___',
                options: [
                  { label: 'on videos online.' },
                  { label: 'clips of shows these days, not full programmes.', correct: true },
                  { label: "podcasts when I'm on the bus or train." },
                  { label: "a video because I don't like to see myself onscreen." },
                  { label: 'photos of my dinner with friends.' },
                  { label: 'online posts carefully before I share them.' },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'Complete: I often listen to ___',
                options: [
                  { label: 'on videos online.' },
                  { label: 'clips of shows these days, not full programmes.' },
                  { label: "podcasts when I'm on the bus or train.", correct: true },
                  { label: "a video because I don't like to see myself onscreen." },
                  { label: 'photos of my dinner with friends.' },
                  { label: 'online posts carefully before I share them.' },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: "Complete: I wouldn't make ___",
                options: [
                  { label: 'on videos online.' },
                  { label: 'clips of shows these days, not full programmes.' },
                  { label: "podcasts when I'm on the bus or train." },
                  { label: "a video because I don't like to see myself onscreen.", correct: true },
                  { label: 'photos of my dinner with friends.' },
                  { label: 'online posts carefully before I share them.' },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'Complete: I often share ___',
                options: [
                  { label: 'on videos online.' },
                  { label: 'clips of shows these days, not full programmes.' },
                  { label: "podcasts when I'm on the bus or train." },
                  { label: "a video because I don't like to see myself onscreen." },
                  { label: 'photos of my dinner with friends.', correct: true },
                  { label: 'online posts carefully before I share them.' },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'Complete: I always edit my ___',
                options: [
                  { label: 'on videos online.' },
                  { label: 'clips of shows these days, not full programmes.' },
                  { label: "podcasts when I'm on the bus or train." },
                  { label: "a video because I don't like to see myself onscreen." },
                  { label: 'photos of my dinner with friends.' },
                  { label: 'online posts carefully before I share them.', correct: true },
                ],
              },
            ],
          },
        },
        {
          type: 'callout',
          title: '6B Talk about it',
          titleAr: '6ب: تحدّث عن ذلك',
          tone: 'tip',
          text: 'Which of the sentences in Ex 6A are true for you? Tell your partner and give reasons. For example: I never comment on videos online. I don\u2019t like the idea of sharing my personal data with strangers.',
          textAr:
            'أي من الجمل في التمرين 6A صحيحة بالنسبة لك؟ أخبر زميلك واذكر الأسباب. على سبيل المثال: لا أعلّق أبداً على فيديوهات على الإنترنت، وأنا لا أحبّ فكرة مشاركة بياناتي الشخصية مع الغرباء.',
        },
        {
          type: 'text',
          title: 'Reading: How YouTube changed my life',
          titleAr: 'قراءة: كيف غيّر يوتيوب حياتي',
          paragraphs: [
            'When I posted my first videos on YouTube, I never thought I would be able to make so many friends. I was studying in London, and I couldn\u2019t meet many people. I had a lot of free time, so I spent a few afternoons making some short videos and uploading them to YouTube. I tried a few different types of video. I started with instructional videos about how to do well at the video games I was playing. In the first few weeks, hundreds of people liked and commented on the videos. Lots of viewers also shared the videos with their friends. At first, I had a few hundred followers, but after six months I had thousands. It was amazing. I had to learn how to make my videos better, by editing them and adding music. Now, I\u2019m doing a course in video game design.',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8r-9a',
            title: '9A Choose the correct option',
            kind: 'mcq',
            instructions: 'Choose the correct option (A\u2013C) to complete the text.',
            instructionsAr: 'اختر الخيار الصحيح (أ–ج) لإكمال النص.',
            page: 103,
            verified: false,
            needsReview: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'I never thought I would \u2026 so many friends.',
                options: [
                  { label: 'be able to', correct: true },
                  { label: 'able to', correct: false },
                  { label: 'can', correct: false },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'I was studying in London, I \u2026 many people.',
                options: [
                  { label: "couldn't", correct: true },
                  { label: "wasn't able", correct: false },
                  { label: "can't", correct: false },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'I spent a few afternoons \u2026 some short videos and uploading them to YouTube.',
                options: [
                  { label: 'making', correct: true },
                  { label: 'to make', correct: false },
                  { label: 'made', correct: false },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'I started with \u2026 videos about how to do well at the video games I was playing.',
                options: [
                  { label: 'instructional', correct: true },
                  { label: 'funny animal', correct: false },
                  { label: 'fitness', correct: false },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'In the first few weeks, hundreds of people \u2026 and commented on the videos.',
                options: [
                  { label: 'liked', correct: true },
                  { label: 'made', correct: false },
                  { label: 'installed', correct: false },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'Lots of \u2026 also \u2026 the videos with their friends.',
                options: [
                  { label: 'viewers \u2026 shared', correct: true },
                  { label: 'likes \u2026 edited', correct: false },
                  { label: 'comments \u2026 installed', correct: false },
                ],
              },
              {
                id: 'q7',
                kind: 'mcq',
                prompt: 'I had to learn how to make my videos better, by \u2026 them and adding music.',
                options: [
                  { label: 'editing', correct: true },
                  { label: 'arranging', correct: false },
                  { label: 'repairing', correct: false },
                ],
              },
              {
                id: 'q8',
                kind: 'mcq',
                prompt: "Now, I'm doing a course in video \u2026 design.",
                options: [
                  { label: 'game', correct: true },
                  { label: 'music', correct: false },
                  { label: 'television', correct: false },
                ],
              },
            ],
          },
        },
        {
          type: 'callout',
          title: 'Discuss',
          titleAr: 'ناقش',
          tone: 'tip',
          text: 'Work in pairs and discuss the questions. Do you know anyone who uploads videos online? What sorts of videos do they post? Do they have a lot of followers?',
          textAr: 'اعملوا في أزواج وناقشوا الأسئلة. هل تعرف شخصاً يرفع فيديوهات على الإنترنت؟ ما أنواع الفيديوهات التي ينشرها؟ هل لديه عدد كبير من المتابعين؟',
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8r-7a',
            title: '7A Complete the conversations',
            kind: 'fill-blank',
            instructions: 'Complete the conversations with one word in each gap.',
            instructionsAr: 'أكمل المحادثات بكلمة واحدة في كل فراغ.',
            page: 103,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: "A: The printer isn't working. Again. B: Yes, it's been",
                answer: 'out',
                after: 'of order all week.',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'A: I waited for hours to speak to someone and then they',
                answer: 'cut',
                after: 'me off. B: I\u2019d be furious!',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: 'A: Have you downloaded the files? B: Not yet. I have a really slow internet',
                answer: 'connection',
                after: 'right now.',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'A: Did you order those trainers? B: No, I\u2019ve',
                answer: 'forgotten',
                accept: ['forgot'],
                after: 'my password for the account.',
              },
            ],
          },
        },
        {
          type: 'callout',
          title: 'Talk about it',
          titleAr: 'تحدث عن ذلك',
          tone: 'tip',
          text: 'Work in pairs and discuss. Which of the problems in Ex 7A are the most annoying?',
          textAr: 'اعملوا في أزواج وناقشوا. أي مشكلة من المشاكل في التمرين 7A هي الأكثر إزعاجاً؟',
        },
        {
          type: 'exercise',
          exercise: {
            id: 'u8-8r-8a',
            title: '8A Replace the words in bold with phrasal verbs',
            kind: 'fill-blank',
            instructions: 'Replace the words in bold with the phrasal verbs from the box: look after, pick up, get on well with, come up with, work out, take up.',
            instructionsAr: 'استبدل الكلمات المكتوبة بالخط العريض بالأفعال المركّبة الموجودة في الصندوق: look after, pick up, get on well with, come up with, work out, take up.',
            page: 103,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: '1 I don\u2019t',
                answer: 'look after',
                after: 'my things, so they often break or I lose them. (take care of)',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: '2 I find it easy to',
                answer: 'pick up',
                after: 'languages quickly. (learn)',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: '3 I',
                answer: 'get on well with',
                after: 'my boss. (have a good relationship with)',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: '4 I don\u2019t like writing stories because it\u2019s difficult for me to',
                answer: 'come up with',
                after: 'ideas. (think of)',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: '5 It takes me a long time to',
                answer: 'work out',
                after: 'maths problems. (solve)',
              },
              {
                id: 'q6',
                kind: 'fill-blank',
                before: '6 I don\u2019t want to',
                answer: 'take up',
                accept: ['start'],
                after: 'playing golf. It\u2019s really boring and expensive. (start)',
              },
            ],
          },
        },
        {
          type: 'callout',
          title: '8B Guess about your partner',
          titleAr: '8ب: خمّن عن زميلك',
          tone: 'tip',
          text: 'Work with a partner. Guess if the sentences in Ex 8A are true for your partner. Use the phrasal verbs from the box. For example: I don\u2019t think sentence 1 is true. I think you look after your things \u2013 you are always tidy.',
          textAr: 'اعمل مع زميلك. خمّن ما إذا كانت الجمل في التمرين 8A صحيحة بالنسبة لزميلك. استخدم الأفعال المركّبة من الصندوق. على سبيل المثال: لا أعتقد أن الجملة الأولى صحيحة، وأعتقد أنك تعتني بأشياءك لأنك دائماً مرتب.',
        },
        {
          type: 'pages',
          images: [img(117, 'Extra review 8R, page 103')],
        },
      ],
    },
  ],
}